tensorflow/swift-models

- Autoencoder/README.md
was seeing crazy errors including 
Symbol not found: __PyCodecInfo_GetIncrementalDecoder
Fatal error: 'try!' expression unexpectedly raised an error: exception: dlopen(/Users/jpope/miniconda2/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
Referenced from: /Users/jpope/miniconda2/lib/python2.7/lib-dynload/_io.so
Expected in: flat namespace
in /Users/jpope/miniconda2/lib/python2.7/lib-dynload/_io.so: file /usr/local/src/swift-build/swift/stdlib/public/core/ErrorType.swift, line 185
0  swift                    0x000000011301e258 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x000000011301d497 llvm::sys::RunSignalHandlers() + 39
2  swift                    0x000000011301e8d2 SignalHandler(int) + 258
3 …
> ⛳️path fix

- MNIST/MNIST.swift
There were some concerns that Foundation would not be readily available. Converting file reading to use python instead.
> Converting MNIST over to use python

- ResNet/ResNet.swift
- ResNet/main.swift
Needs https://github.com/apple/swift/pull/22112 and https://github.com/rxwei/DeepLearning/pull/1, plus https://github.com/apple/swift/pull/22057 when it's ready.
> ResNet demo

- ResNet/ResNet50.swift
Drop `LearningPhaseIndicator`.
> Switch ResNet to using the new layer API.

- Gym/CartPole.swift
On a Linux GPU env, it took ~25 mini batches (batch size 16) to solve (i.e.,
trained to converged) with Adam optimizer. Hyper params such as learning rate have not been well tuned.
Some print statements (including commented out ones) are intentionally left
around for debugging purposes.
> A simple RL model solving the CartPole problem from OpenAI gym.

- Catch/catch.swift
This PR contains minimal changes required to make Catch make use of the deep learning library, and minimal changes that attempt to correct the algorithm.
- We do not yet have a VJP for `Tensor.max()` in the library, so `𝛁loss` is not computed via automatic differentiation.
- Use reward from the previous step for correctness. It only improves learning a little bit, however.
- Change `Environment.observation()` and `Environment.reward()` to computed properties as their computation is trivial.
- Not print rewards.
> Update Catch to use the deep learning library.

- Gym/FrozenLake.swift
This model does not use a neural net, and instead demonstrates Swift host-side
numeric processing as well as python integration.
This model took ~30 seconds to solve on my Linux desktop (CPU only computation).
https://bugs.swift.org/browse/TF-170
> Solves the FrozenLake RL problem via Q-learning.

- MiniGo/README.md
Update README.md.
Installation/usage instructions are verified.
> Update MiniGo documentation.

- CIFAR/main.swift
- CIFAR/models.swift
The code to download the CIFAR images does not run on macOS, but the example trains if you download the data manually. A fix for downloading can probably wait until Dataset functionality is complete.
> Update for release 0.2

- CIFAR/README
- CIFAR/data.swift
- CIFAR/main.swift
- CIFAR/models.swift
Edit: switched to `sequenced(in:through:)`
Edit again: switched back
> Update CIFAR models for API changes

- Transformer/Model.swift
- Transformer/Operators.swift
- Transformer/PythonCheckpointReader.swift
- Transformer/README.md
- Transformer/main.swift
Also fixes some formatting issues.
I added a `-ltensorflow` flag to the compiler command in the README because it appears to be needed with the release toolchain when using `#tfop`.
> Address rxwei@'s comments on Transformer model

- ResNet/ResNet50.swift
labels --> oneHotLabels
Fixes #67.
> tweak resnet variable name

- CIFAR/resnet.swift
this all works, but if anybody has any suggestions on how to refactor it I would love to hear them!
> add resnet 20/32/44/56 variants

- MNIST/main.swift
@rxwei is this the correct idea?  if you like this approach, happy to redo the vision models!
running this on my lowly 2080ti here produces this error, am I doing something wrong?
recompiling then will test w/ cpu mode as well.
```
>swift run MNIST
Reading data.
Constructing data tensors.
[Epoch 1] Loss: 926.598, Accuracy: 55181/60000 (0.91968334)
Fatal error: OOM when allocating tensor with shape[100,32,26,26] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc: file /home/skoonce/swift/swift-source/swift/stdlib/public/TensorFlow/CompilerRuntime.swift, line 2090
Current stack trace:
0    libswiftCore.so                    0x00007fa96a320c80 _swift_stdlib_reportFatalErrorInFile + 115
1    libswiftCore.so                    0x00007fa96a26983c <unavailable> …
```
> rework mnist for layer api changes

- CIFAR/resnet.swift
- ResNet/ResNet50.swift
- ResNet/ResNetV2.swift
- ResNet/data.swift
- ResNet/main.swift
@rxwei took the stable branch, dropped 6a2f4e6139530d11e209a4f28d4ac4ce78b24a28 and 99920f52ed1cf57cd592d18cb00149ecb2acb91e, then rebased on master and merged for a clean tree.  let me know if you prefer a different method.
> Stable rebase

- Gym/CartPole.swift
@rxwei okay, the new problem is that there are models both in stable and then new dev has been done against master.  how do you want to get things in sync?  happy to redo my pr's if that is simpler.  otherwise would be better to do a sync before doing significant cleanup that will have to be rebased later.
> update cartpole for 0.3

- CIFAR/wide_resnet.swift
* add wide resnet 16/28 variants
* update wide resnet for 0.3
* simplify layer names
* rework formatting for line length
> add wide resnet 16/28 variants

- Transformer/Model.swift
- Transformer/Operators.swift
- Transformer/PythonCheckpointReader.swift
- Transformer/main.swift
Tested on swift-tensorflow-DEVELOPMENT-2019-04-16-a-osx.pkg.
> Updated Transformer model to latest Swift For TensorFlow build

- CIFAR/main.swift
- Gym/CartPole.swift
- MNIST/main.swift
- ResNet/main.swift
#101 remains the status quo after this
> grabbag of int fixes

- Autoencoder/Autoencoder.swift
Closes #93.
@rxwei Reverted to #19, then backported as many tweaks/fixes on top as I could.  Will need to be re-modernized, so to speak, but works.  Happy to redo the formatting if you are okay with this approach.
> rework autoencoder for 0.3

- MiniGo/Models/GoModel.swift
- MiniGo/Strategies/MCTS/MCTSModelBasePredictor.swift
> Updated MinoGo to compile and run using latest Swift for TensorFlow

- MiniGo/GameLib/BoardState.swift
- MiniGo/GameLib/Color.swift
@rxwei this cherrypicks the only outstanding commit from stable onto master.
merge, then you can
checkout stable, checkout -b stable-0.2, push to origin
and then
checkout -D stable (deletes local stable branch)
checkout master, checkout -b stable, push (and replace current stable with -f or delete before pushing)
and then close #124.
> Conforms `Color` enum in MiniGo example to CaseIterable (#117)

- MiniGo/Play/PlayOneGame.swift
Replaces array access with indexing instead of first and last as was discussed with @rxwei
> Replaces array access with indexing instead of first and last

- Autoencoder/main.swift
- CIFAR/data.swift
- CIFAR/main.swift
- CIFAR/models.swift
- CIFAR/resnet.swift
- CIFAR/wide_resnet.swift
- Catch/main.swift
- Gym/CartPole/main.swift
- Gym/FrozenLake/main.swift
- MNIST/main.swift
- ResNet/ResNet50.swift
- ResNet/ResNetV2.swift
- ResNet/data.swift
- ResNet/main.swift
- Tests/MiniGoTests/GameLib/BoardStateTests.swift
- Tests/MiniGoTests/GameLib/XCTestManifests.swift
- Tests/MiniGoTests/Models/GoModelTests.swift
- Tests/MiniGoTests/Strategies/MCTS/MCTSModelBasedPredictorTests.swift
- Tests/MiniGoTests/Strategies/MCTS/MCTSNodeTests.swift
- Tests/MiniGoTests/Strategies/MCTS/MCTSPolicyTests.swift
- Transformer/Model.swift
- Transformer/Operators.swift
- Transformer/PythonCheckpointReader.swift
- Transformer/main.swift
* Add a copyright header to every file.
* Make sure every copyright header has `2019` instead of `2018`.
* Tidy up ResNet a bit.
> Add copyright headers and tidy up ResNet.

- Transformer/Model.swift
- Transformer/Operators.swift
just made these changes to compile against the latest master, not sure if this the correct approach, please review.  seems to be working in the console:
> ./main 0.7 "Swift for Tensorflow is "
Swift for Tensorflow is  a full-stack implementation of the Tensorflow library (it's much better than the inspired Prezi ), which is a simple on-stack framework for Tensorflow, which also features a few toolkit features, such as Flow, Iterator, and Cartesian functions. This is a great way to make your Tensorflow code (or at least in my case, my code) more flexible and easier to use.
> transformer: upstream api changes

- ResNet/Helpers.swift
- ResNet/ResNet50.swift
- ResNet/main.swift
> rebuild resnet block based approach

- Models/ImageClassification/WideResNet.swift
(cherry picked from commit db72e4ddb7d1fe15915689dc531abac330266731)
> Fix '@noDerivative' warnings. (#208)

- Transformer/Model.swift
> use enable in _vjpCausallyMasked

- Models/ImageClassification/VGG.swift
- Tests/ImageClassificationTests/Inference.swift
not sure what all should have the public keyword
> rewrite vgg to use blocks, add vgg 19

- Datasets/CIFAR10/CIFAR10.swift
- Datasets/ImageClassificationDataset.swift
- Datasets/MNIST/MNIST.swift
[reference](https://www.cs.toronto.edu/~kriz/cifar.html)
> Also set number of test examples on CIFAR10

- Models/Text/main.swift
@dan-zheng this is what we discussed earlier. Please let me know if the model seems to be learning once you add the evaluation function call. :)
> Made some minor edits to get the BERT classifier training to work for CoLA.

- Datasets/Imagenette/Imagewoof.swift
- Examples/VGG-Imagewoof/README.md
- Examples/VGG-Imagewoof/main.swift
can be unified with primary namespace for sure, but not sure what pattern you all would like
> add imagewoof dataset

- Datasets/BostonHousing/BostonHousing.swift
this makes this work on my system, but is probably not the right way to solve this... 🤫
> tweak boston data getter to work on linux

- CMakeLists.txt
- FastStyleTransfer/CMakeLists.txt
- MiniGo/CMakeLists.txt
- Models/ImageClassification/CMakeLists.txt
- Support/CMakeLists.txt
- Tests/CMakeLists.txt
- Tests/CheckpointTests/CMakeLists.txt
- Tests/DatasetsTests/CMakeLists.txt
- Tests/FastStyleTransferTests/CMakeLists.txt
- Tests/ImageClassificationTests/CMakeLists.txt
- Tests/MiniGoTests/CMakeLists.txt
Add support for tests to CMake to enable running the test suite on
Windows.
> build: add testing support to the CMake build

- Models/Text/BytePairEncoding.swift
- Package.swift
- Transformer/CMakeLists.txt
- Transformer/README.md
- Transformer/TransformerLoop.swift
- Transformer/UI/Windows/TransformerUI.exe.manifest
- Transformer/UI/Windows/main.swift
- Transformer/main.swift
This adds a simple UI wrapper for the transformer demo.
> Transformer: add a simple UI wrapper for GPT-2

- README.md
Add example command lines to demonstrate how to run the test suite via
CMake.
> docs: update documentation on how to test with CMake

- Support/Checkpoints/CheckpointIndexWriter.swift
The index, meta index, and footer blocks have been completed, leading to the generation of checkpoint files that can be read by TensorFlow 1.x / 2.x.
This has been tested with the GPT-2 Transformer model, where checkpoints saved from the swift-models Transformer example can be loaded using [the original OpenAI implementation in TensorFlow 1.x](https://github.com/openai/gpt-2). One slight modification needs to be made to that Python model in that the initial dimension of 1 in [the weights here](https://github.com/openai/gpt-2/blob/master/src/model.py#L53) needs to be removed (changing shape to `[nx, nf]`), because our Dense layers don't have that extra dimension.
> Making CheckpointWriter generate TensorFlow 1.x / 2.x compatible checkpoints

- Models/Text/GPT2/GPT2.swift
- Tests/TextTests/Inference.swift
> Replace endoftext token with newline

- Models/Text/GPT2/GPT2.swift
- Tests/TextTests/Inference.swift
- Transformer/UI/Windows/main.swift
> Universal linebreaks

- README.md
- Transformer/README.md
Add instructions on how to get started with the TransformerUI demo on
Windows.
> docs: add steps for building the TransformerUI demo

- Examples/GPT2-Inference/README.md
- README.md
Update GPT2-Inference README for consistency with root README.
Follow-up from #412
> Replace drive letter with %SystemDrive% in win commands

- Models/ImageClassification/CMakeLists.txt
- Models/ImageClassification/MobileNetV3.swift
- Tests/ImageClassificationTests/Inference.swift
the first commit is the one in #408, was reusing block names and so this requires to be built on top of that branch.
> add mobilenet v3

- Datasets/TextUnsupervised/TextUnsupervised.swift
- Models/Text/GPT2/TransformerLM.swift
- Support/Text/BytePairEncoder.swift
1. TextUnsupervised.swift: make number of documents to process configurable
2. TransformerLM.swift 
- make device consistent while calling bandPart
- make layers to be 'var' to be copiable.
3. BytePairEncoder.swift: set 'limitedBy' to avoid String index is out of bounds FatalError
> Fixes to make GPT2-WikiText2 trained on TPU with x10

- README.md
Looks like a copy-paste artifact.
> Windows: fix repo path in README.md

- Models/Text/Attention.swift
- Models/Text/TransformerBERT.swift
- Models/Text/Utilities.swift
- Models/Text/WeightDecayedAdam.swift
- Support/Text/Tokenization.swift
This resolves device mismatch runtime failures when running on XLA.
> [BERT] Specify devices explicitly

- Models/ImageClassification/CMakeLists.txt
- Models/ImageClassification/ShuffleNetV2.swift
- Tests/ImageClassificationTests/Inference.swift
This model introduces channel shuffling, so I thought it would be a good addition to the classification family.
> Add ShuffleNetV2

- Models/ImageClassification/ShuffleNetV2.swift
Patch for release branch, equivalent to #479
> [ShuffleNetV2] Resolve warning about non-mutating var

- Examples/MobileNetV1-Imagenette/README.md
Fix incorrect run command in the MobilenetV1 example readme.
> [MobilenetV1] Fix run command in readme

- Models/Text/BERT.swift
- Models/Text/CMakeLists.txt
- Models/Text/RegularizableEmbedding.swift
Fixes #493
Change filename and all references.
> [BERT] Rename custom embedding layer

- Models/Text/WordSeg/Lattice.swift
- Models/Text/WordSeg/SemiRing.swift
> One LogSumExp to bring them all

- Models/Text/WordSeg/Model.swift
`Tensor.scalarsADHack` exists as a workaround for TF-1008.
It is currently needed for correctness.
Reorganize code and optimize captured values in the `scalarsADHack` pullback.
No functional fixes in this commit.
> [WordSeg] Clarify autodiff workaround for `Tensor.scalars`.

- Autoencoder/Autoencoder2D/main.swift
A similar PR to https://github.com/tensorflow/swift-models/pull/532
> Switch off OldKuzushijiMNIST in Autoencoder2D

- Models/Text/WordSeg/Model.swift
Add dropout to `SNLM.encode` and `SNLM.decode`.
Make all dropout invocations more visible using local variable mutations.
> [WordSeg] Add dropout to SNLM.

- Autoencoder/VAE1D/main.swift
> Switch off OldMNIST in VAE1D

- Examples/WordSeg/main.swift
Automatically reduce the learning rate when training loss stagnates.
Move training termination code into a function to reduce clutter in the main loop.
> [WordSeg] Reduce learning rate on plateau

- Datasets/CMakeLists.txt
- Datasets/ImageSegmentationDataset.swift
- Datasets/OxfordIIITPets/OxfordIIITPets.swift
- Tests/DatasetsTests/CMakeLists.txt
- Tests/DatasetsTests/OxfordIIITPets/OxfordIIITPetsTests.swift
A fresh pull request for the addition of Oxford IIIT Pets Dataset as #470 had conflicts that were difficult to resolve.
> Added Oxford-IIIT-Pets Dataset

- Examples/BERT-CoLA/README.md
> [BERT] NFC: fix typo.

- Package.swift
see also https://github.com/apple/swift-protobuf/pull/975
> bump swift-protobuf to 1.9.0

- CycleGAN/Data/Dataset.swift
- CycleGAN/main.swift
This PR resolves item 1 in https://github.com/tensorflow/swift-models/issues/582
> Switch off Batcher from CycleGAN

- pix2pix/Dataset.swift
- pix2pix/main.swift
Resolving part of https://github.com/tensorflow/swift-models/issues/582
> Switch off Batcher from Pix2Pix

- Datasets/MovieLens/MovieLens.swift
- Examples/NeuMF-MovieLens/main.swift
Continue the process described in https://github.com/tensorflow/swift-models/issues/592
> Convert NeuMF-MovieLens to Epoches

- Examples/WordSeg/main.swift
WordSeg dataset br-text contains 7832 training examples and it take 1 to 2 hours to train through them in one epoch. If we follow the regular pattern where we print the statistics only in the end of the epoch, the console will keep silent for 1~2 hours. So I change to print every 10 examples and this is also what tf-python does.
> WordSeg training: print progress every 10 examples

- Examples/Notebooks/LanguageModel.ipynb
As part of https://github.com/tensorflow/swift-models/issues/592
> Update LanguageModel notebook with Epochs

- Models/Text/WordSeg/Model.swift
Within the `encode()` and `decode()` method, we noticed that two dropout-related calculations were using `var`s for intermediate values. In the backward pass, this was leading to the generation of AD-related code that was unnecessary for performing this calculation.
By converting these to `let`s, we remove ~200 zeroes in the backwards pass in the WordSegScoreAndGradient benchmark at sentence size 4, and the backwards pass improves in throughput by ~3%.
> Minor optimization, removing some vars within WordSeg

- Package.swift
> bump swift-protobuf to 1.10.0

- BenchmarksCore/BenchmarkArguments.swift
- Examples/WordSeg/WordSegCommand.swift
So the new build(nightly) has been throwing some warnings, this is just updating the calls to suppress those.
> Update calls to suppress build warnings

- Models/Text/WordSeg/Lattice.swift
- Models/Text/WordSeg/Model.swift
Register a derivative for `Lattice.subscript.set` to make it differentiable.
Use `Lattice.subscript.set` in WordSeg model code to make it more idiomatic.
> [WordSeg] Make `Lattice.subscript.set` be differentiable.

- Datasets/TextUnsupervised/TextUnsupervised.swift
- Examples/GPT2-WikiText2/CMakeLists.txt
- Examples/GPT2-WikiText2/main.swift
- Package.swift
- TrainingLoop/Metrics.swift
Also make the training on XLA by default.
> Convert GPT2-WikiText2 to TrainingLoop

- Autoencoder/Autoencoder1D/CMakeLists.txt
- Autoencoder/Autoencoder1D/main.swift
- Autoencoder/CMakeLists.txt
- Autoencoder/Callback/CMakeLists.txt
- Autoencoder/Callback/ImageSaver.swift
- Autoencoder/Callback/SaveImage.swift
- Package.swift
This will allow the callback shared by all autoencoder variants.
> Take autoencode saveImage callback to common place

- Tests/TextTests/WordSegmentationTests/ProbeLayers.swift
See https://bugs.swift.org/browse/SR-13945 for more info.
> Work around SR-13945 segfault.

- Datasets/Imagenette/ImageNet.swift
`blacklist` -> `denylist`
Some light reformatting included.
> Use respectful language.
