tensorflow/swift-models

- MNIST/MNIST.swift
1. Normalized a few gradient values by the bach size.
2. Changed the loss function from MSE to cross entropy, which works with the
hard-coded gradients.
The change of loss values across training iterations before this CL:
Begin training for 20 iterations.
0.9
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.177527
0.25868
0.581863
0.18193
0.1
0.1
0.1
0.1
0.1
0.177527
0.1
0.1
After this CL:
Begin training for 20 iterations.
nan
113.156
88.0401
62.9524
38.1512
16.3276
5.25584
3.61207
3.37472
3.30145
3.2731
3.26038
3.2549
3.25211
3.25062
3.2499
3.24947
3.2495
3.24934
3.24926
3.24926
There might be further tuning opportunities with learning rate, etc, but is beyond the scope of this CL.
Working on this CL exposed a few compiler bugs. Left FIXME comments accordingly,
and will file bugs.
> A few fixes to the MNIST model:

- Catch/catch.swift
Rewrite model using bare `Tensor` values, since the experimental high-level API has been removed.
Tested with [pre-built packages from 6/22](https://github.com/tensorflow/swift/blob/master/Installation.md#pre-built-packages).
Resolves #7.
> Rewrite Catch without high level APIs

- Autoencoder/Autoencoder.swift
- MNIST/MNIST.swift
- `Tensor.dot(_:)` and `⊗` were deprecated in favor of `matmul(_:_:)` and `•`.
- `toDevice` was renamed to `toAccelerator`.
> Use updated APIs (`•` and `toAccelerator`).

- MNIST/MNIST.swift
Update MNIST model to adopt `ParameterAggregate` synthesis.
Also:
* Since most bugs have been fixed, remove workarounds on scalar promotion, partitioning crashers and send/receive crashers.
* `Tensor.transposed` does not need to specify permutations.
* A `main()` function conveys a wrong message about the programming model. Swift supports and encourages top-level code for training scripts. `main()` has been changed to `train(_:iterationCount:)`, a function that actually has a meaning.
* Code in swift-models does not need to fit within 80 columns.
* `readMnist` -> `readMNIST`
> Update MNIST model to adopt ParameterAggregate synthesis.

- Autoencoder/Autoencoder.swift
- MNIST/MNIST.swift
Plus some fixes:
* Remove the single-case `AutoencoderError` enum. Data loading for this simple model won't fail in multiple ways, so optionals should be preferred.
* Move everything from `main()` to top level.
> Adopt derived 'Parameterized' conformance in the Autoencoder model.

- Autoencoder/Autoencoder.swift
- MNIST/MNIST.swift
Using `CommandLine.arguments[0]` to get the Swift script location is
unrobust. `arguments[0]` differs when running `swift` directly vs.
invoking `swiftc` then running the compiled binary.
> Use `#file` to get Swift script location.

- MNIST/MNIST.swift
* Implement minibatch gradient descent.
* TODO: Randomly sample minibatches using TensorFlow dataset APIs.
* Print accuracy (rather than loss) to clearly show that the model is improving.
Example output:
```
Reading data.
Constructing data tensors.
Begin training for 20 epochs.
Accuracy: 53172/60000 (0.8862)
Accuracy: 55651/60000 (0.92751664)
Accuracy: 56104/60000 (0.93506664)
Accuracy: 56390/60000 (0.93983334)
Accuracy: 56576/60000 (0.9429333)
Accuracy: 56810/60000 (0.9468333)
Accuracy: 56968/60000 (0.94946665)
Accuracy: 57105/60000 (0.95175)
Accuracy: 57228/60000 (0.9538)
Accuracy: 57358/60000 (0.95596665)
Accuracy: 57347/60000 (0.9557833)
Accuracy: 57357/60000 (0.95595)
Accuracy: 57367/60000 (0.9561167)
Accuracy: 57540/60000 (0.959)
Accuracy: 57545/60000 (0.9590833)
Accuracy: …
```
> [MNIST] Implement minibatch gradient descent and print accuracy.

- Autoencoder/Autoencoder.swift
- MNIST/MNIST.swift
This is basically removing a bug workaround.
Runs correctly with compiler rev [1e79e03](https://github.com/apple/swift/tree/1e79e03cc628090f73e589064feb909129b34c54).
> Use a loop to express running 5 steps

- CIFAR/data.swift
- CIFAR/main.swift
- CIFAR/models.swift
- ResNet/ResNet50.swift
These are intended to match the networks used in the canonical PyTorch 
and Keras CIFAR10 examples, but they don't currently converge to the 
correct loss. Requires https://github.com/rxwei/DeepLearning/pull/4 but no
compiler changes.
> Add a pair of convolutional models for CIFAR10 image classification

- Transformer/README.md
* adds parameter for `download_model.sh`
* adds parameter `-o main` for `swiftc` to make following examples work
> Fixes README for Transformer

- CIFAR/data.swift
- CIFAR/main.swift
- ResNet/data.swift
- ResNet/main.swift
https://github.com/apple/swift/commit/bcb73a17770da5b891fb8cfbc647c6425bf30e53 remoted the TensorPair struct.
> Remove uses of the obsolete TensorPair struct from models.

- README.md
I believe that our intended purpose is that the "stable" branch works with the latest "Release" builds (e.g. v0.2 right now). So I have clarified this in the Readme. Let me know if I'm confused!
> clarify the purpose of the "stable" branch

- MNIST/README.md
- MNIST/main.swift
- Package.swift
1. Rename the mnist.swift to main.swift so swiftpm can find it.
2. Improve the readFile method to search folders. This is required as we are changing the folder to run it. 
3. Give a better error message when file cannot be found.
> Convert MNIST to Swift Manager

- CIFAR/README.md
- CIFAR/main.swift
- Package.swift
- ResNet/README.md
- ResNet/main.swift
In addition to the changes mentioned in the title, I did the same change for CIFAR regarding the py3 issue.
> Convert ResNet to SwiftPM and add notes how to run it with Py3.

- CIFAR/main.swift
- CIFAR/models.swift
- CIFAR/resnet.swift
@rxwei this all works, but could be refactored down more.
I am getting this error when I try to use through on my Conv2DBatchNorm Layer, should I be doing something differently?
```
resnet.swift:133:26: error: cannot invoke 'sequenced' with an argument list of type '(through: Conv2DBatchNorm
)'                                                                                                            
let test = input.sequenced(through: inputLayer)                                                       
^                                                                                    
resnet.swift:133:26: note: overloads for 'sequenced' exist with these partially matching parameter lists: (thr
ough: L1, L2), (through: L1, L2, L3), (through: L1, L2, L3, L4), (through: L1, L2, L3, L4, L5), …
```
> update cifar models for 0.3

- MNIST/MNIST.swift
We don't need numpy to read files in Swift.
> Gets rid of Python in MNIST example

- MNIST/main.swift
@rxwei if this is the correct pattern, I can bang out the other ones!
> update mnist for new layers api

- MiniGo/README.md
Doing 
swift run -Xlinker -ltensorflow -c release MiniGo
like the README suggests in the parent directory is currently failing because the logic assumes it is in the MiniGo directory.  On the flip side doing a ```swift run``` inside the MiniGo directory will fail if this get merged.  Not sure what the correct/desired behavior is.  Can also write logic to check both locations but figured I would ask first.
> tweak checkpoint directory to match README?

- MNIST/main.swift
@rxwei clean rebase of #106 on master:
Gets rid of Python in MNIST example (#108)
* Get rid of Python in MNIST example. We don't need numpy to read files in Swift
* Gets rid of closures in map
* Renames parameter
> cherry-pick 21ae62e6de2298074de153782d66a32a36b10f58

- Transformer/Model.swift
- Transformer/Operators.swift
- Transformer/main.swift
I have to use `.call` explicitly for callable with `inout`. Once "Static callable does not support `inout`" (https://bugs.swift.org/browse/TF-443) get fixed, we can simply remove `.call` in the code.
> Updated Transformer model to use `callable`.

- MiniGo/Strategies/MCTS/MCTSNode.swift
- Tests/MiniGoTests/Models/GoModelTests.swift
- Tests/MiniGoTests/Strategies/MCTS/MCTSModelBasedPredictorTests.swift
- Two are due to the the compiler/stdlib changes.
- one is due to https://github.com/tensorflow/swift-models/pull/119/
> Fixed the MiniGo Tests due to recent changes.

- MiniGo/Models/GoModel.swift
- MiniGo/Strategies/MCTS/MCTSModelBasePredictor.swift
- MiniGo/Strategies/MCTS/MCTSPredictor.swift
- Tests/MiniGoTests/Models/GoModelTests.swift
- Tests/MiniGoTests/Strategies/MCTS/MCTSModelBasedPredictorTests.swift
- Rename `InferenceModel`'s `prediction(input:)` to `prediction(for:)`.
- Rename `GoModel._vjpApplied(to:)` to `GoModel._vjpCall(_:)`.
- Minor formatting changes.
- Remove outdated comments about `Int32` indices.
> Minor cleanup for MiniGo.

- Gym/CartPole/main.swift
- Gym/FrozenLake/main.swift
* Fit to 100 columns.
* Use the new learning phase API more precisely around gradient calculation. Though it doesn't matter at all because we only have dense layers, it's better for education purposes.
* Very minor terminology spelling improvements.
> Minor code formatting pass on Gym models.

- MiniGo/GameLib/Board.swift
- MiniGo/GameLib/BoardState.swift
- MiniGo/GameLib/Color.swift
- MiniGo/GameLib/GameConfiguration.swift
- MiniGo/GameLib/LibertyTracker.swift
- MiniGo/GameLib/Position.swift
- MiniGo/Models/GoModel.swift
- MiniGo/Models/PythonCheckpointReader.swift
- MiniGo/Play/PlayOneGame.swift
- MiniGo/Strategies/MCTS/MCTSModelBasePredictor.swift
- MiniGo/Strategies/MCTS/MCTSPredictor.swift
- MiniGo/main.swift
- Tests/MiniGoTests/Models/GoModelTests.swift
- Tests/MiniGoTests/Strategies/MCTS/MCTSModelBasedPredictorTests.swift
Logic changes:
* In LibertyTracker.swift, use dictionary indices to avoid force unwrapping. Removed a lot of bangs!
* Make `ModelConfiguration.boardSize` public since the initializer takes a `boardSize` for better transparency. It's a little weird for an initializer to take a constant, store it and make it private.
* Reduce nesting in `LibertyTracker.updateLibertiesAfterRemovingCapturedStones(_:)` with `compactMap(_:)`.
* Simplify `assignNewGroupID()` with a `defer` block.
Formatting changes:
* Make every file end with exactly 1 empty line.
* Add some minor comments.
* Remove empty lines between the start of a type declaration or extension and the first declaration for consistency.
* Make `GoModel` code fit within 100 columns.
> MiniGo style pass and and minor logic enhancements.

- MiniGo/Models/GoModel.swift
Comments no longer apply (AD bug has been fixed and arrays now conform to `Differentiable`)
> Remove deprecated comments +`@noDerivative`

- docker/Dockerfile
This is needed to set up the presubmit for this repo on kokoro.
> Add a DockerFile to the repository.

- .gitignore
- Autoencoder/main.swift
- MNIST/main.swift
As part of the migration to a single SwiftPM-based package for the models
repository, the working directory where people run `swift run` has changed.
As a result, a number of relative-path lookups were broken when actually
running models. This commit fixes them up so they all properly run.
> Fix up models so they can run.

- Autoencoder/main.swift
- MNIST/main.swift
- MiniGo/main.swift
Use `print(_:)` and `exit(_:)` instead of a `fatalError(_:file:line:)` so that the program won't crash when a file doesn't exist.
> Gracefully exit instead of crashing when a file is not found.

- Transformer/Model.swift
See https://bugs.swift.org/browse/TF-516 for additional context.
> Unbreak models by inserting `.call`.

- Autoencoder/main.swift
- CIFAR/Data.swift
- CIFAR/Models.swift
- CIFAR/ResNet.swift
- CIFAR/WideResNet.swift
- Catch/README.md
- Catch/main.swift
- Gym/CartPole/main.swift
- MNIST/main.swift
- MiniGo/Models/GoModel.swift
- ResNet/Data.swift
- ResNet/ResNet50.swift
- ResNet/ResNetV2.swift
- Transformer/Model.swift
- Transformer/Operators.swift
> Updated models to use revised name for callable (SE-0253), fixed a few issues caused by `swift-apis` changes.

- MiniGo/Models/GoModel.swift
New 'Differentiable' derived conformances will not include constant properties in the tangent space.
> Make 'GoModel' stored properties be variables.

- .gitignore
- .swift-format
This replicates the following pull request on swift-apis: https://github.com/tensorflow/swift-apis/pull/374 , adding a `swift-format` configuration file. Note the cautions indicated in that pull request around use of `swift-format` at present.
This also adds a .gitignore line to prevent Xcode 11's new SwiftPM support from adding supporting files to the repository.
> Added .swift-format and updated .gitignore for Xcode 11's SwiftPM support

- .gitignore
- CIFAR/Data.swift
- CIFAR/README.md
- CIFAR/main.swift
- Package.swift
- ResNet/Data.swift
- ResNet/README.md
- ResNet/main.swift
The CIFAR10 dataset download and loading mechanism in the CIFAR and ResNet models was dependent on Python for downloading and parsing the dataset. In particular, this was dependent on Python 3 for the pickle archives of the CIFAR10 dataset, which created a slight barrier for macOS systems that had Python 2 by default.
This replaces the dataset downloading and parsing with a Swift-only implementation, removing the need for Python. It downloads the binary CIFAR10 dataset via FoundationNetworking, and then parses the image and label bytes from that.
As a result, Python 3 is no longer required to train these models, nor is wget.
> Replaced Python with Swift in CIFAR10 dataset loading

- Autoencoder/main.swift
This PR resolves #179 
In v0.4.0-rc2 `sigmoid` has a bug in its gradient. So the model doesn't learn correctly.
It'll be fixed in future release.
close #179
> Replace Autoencoder's tanh activation with sigmoid

- Transformer/Model.swift
- docker/Dockerfile
The toolchain being used is from july 10th, update to current toolchain.
> nightlies URL: s4tf-kokoro-artifact-testing => swift-tensorflow-artifacts

- docker/Dockerfile
Current Dockerfile doesn't install Python requirements.
```sh
$ docker build -t s4tf docker
$ docekr run --rm -v $PWD:/swift-models s4tf swift run Autoencoder
...
Fatal error: 'try!' expression unexpectedly raised an error: Python exception: No module named 'matplotlib': file /swift-base/swift/stdlib/public/Python/Python.swift, line 683
```
Added  `numpy`, `matplotlib`, and `gym` installation.
> Update Dockerfile to install Python libraries

- Models/ImageClassification/ResNet50.swift
Small fix for correctly populating `blocks` with `blockCount` number of `ResidualBasicBlock`s and `ResidualIdentityBlock`s as opposed to `blockCount - 1`.
> [Models] Fix enumeration of blocks in `ResidualBasicBlockStack` `init`

- Models/ImageClassification/WideResNet.swift
replaces #158.  With the repo restructuring and availability of control flow autodiff it seemed simpler to make the changes from scratch.
The changes match the model to the citation by:
- fix widenFactor application so model can train
- use identity shortcuts when the feature size doesn't change
- use preactivation on the shortcut branch when features are expanded
- add dropout between convolutions when feature sizes don't change
- remove extra ReLU following the addition of shortcut and residual
There are other changes that could be made as well but they are across all the residual models.
- use He normal initialisation instead of Glorot uniform
- include L2 regularisation of the model weights in the loss
I tested the changes locally by using `WideResNet(depthFactor: 2, widenFactor: 2)` …
> WideResNet - fix widenFactor and match model to citation

- Autoencoder/main.swift
- Catch/main.swift
- Examples/Custom-CIFAR10/main.swift
- Examples/LeNet-MNIST/main.swift
- Examples/ResNet-CIFAR10/main.swift
- GAN/main.swift
- Gym/CartPole/main.swift
This removes the now-deprecated allDifferentiableVariables from the various training loops. This is a follow-on from this change in swift-apis: https://github.com/tensorflow/swift-apis/pull/419 .
> Remove deprecated allDifferentiableVariables

- .gitignore
- Autoencoder/README.md
- Autoencoder/main.swift
- GAN/README.md
- GAN/main.swift
- Package.swift
- Support/FileManagement.swift
- Support/Image.swift
This adds a wrapper Image struct for encapsulating JPEG (and potentially other formats) image loading and saving, using Raw TensorFlow operators. This allows for JPEG loading and saving without any external dependencies.
To date, Matplotlib had been used for image export, but this provides a means of performing this directly in Swift. As a result, the Matplotlib (and Python, in general) dependencies have been removed for the Autoencoder and GAN examples.
This is a first step for providing general image dataset loading for training and tests.
> Add JPEG loading / saving via Raw TF operations, removing Matplotlib dependencies

- Catch/main.swift
[swift-apis/#497](https://github.com/tensorflow/swift-apis/pull/497) deprecates layer apis, now that we are moving onward to v0.5. This PR updates the catch file which has a deprecated dense layer.
> Update deprecated APIs in Catch

- Models/ImageClassification/SqueezeNet.swift
- Tests/ImageClassificationTests/Inference.swift
So the default activation in conv layers is identity, while the squeezenet paper mentions a relu activation after the 1st and last convolution.
Also adding the v1.1 version of squeezenet, its 2.4x less computation without sacrificing accuracy. For more check [here](https://github.com/DeepScale/SqueezeNet/tree/master/SqueezeNet_v1.1).
> Update squeezenet and add V1.1 version

- Models/ImageClassification/DenseNet.swift
- Models/ImageClassification/DenseNet121.swift
- Tests/ImageClassificationTests/Inference.swift
Any feedback would be awesome.
@rxwei @BradLarson
> DenseNet Implementaion

- MiniGo/Models/GoModel.swift
- Transformer/Model.swift
- Transformer/PythonCheckpointReader.swift
Friend PR: https://github.com/tensorflow/swift-apis/pull/525
> Change momentum and epsilon properties to scalars.

- Datasets/CIFAR10/CIFAR10.swift
- Datasets/MNIST/MNIST.swift
- GAN/main.swift
- MiniGo/Models/PythonCheckpointReader.swift
- Support/Image.swift
- Transformer/Model.swift
- Transformer/Operators.swift
- Transformer/PythonCheckpointReader.swift
- Transformer/main.swift
This addresses the remaining deprecation warnings after PR #221 handles the warning inside MiniGo.
> Fixing deprecation warnings on all but the MiniGo example.

- Autoencoder/main.swift
- Benchmarks/Models/ImageClassificationInference.swift
- Benchmarks/Models/ImageClassificationTraining.swift
- Benchmarks/main.swift
- Datasets/CIFAR10/CIFAR10.swift
- Datasets/ImageClassificationDataset.swift
- Datasets/LabeledExample.swift
- Datasets/MNIST/MNIST.swift
- Examples/Custom-CIFAR10/main.swift
- Examples/LeNet-MNIST/main.swift
- Examples/ResNet-CIFAR10/main.swift
- GAN/main.swift
This addresses the remaining items in issue #206:
- An ImageClassificationDataset protocol has been introduced that both the MNIST and CIFAR10 datasets now conform to.
- Both datasets now use a simpler, common interface.
- MNIST has been reworked to provide the same kind of shuffling and batching that the CIFAR10 dataset does.
As a result, the benchmarks have been made generic over image classification datasets, allowing for that to be specified as part of the benchmark. This removes the hardcoded dependency on MNIST as the only benchmark source dataset.
All example applications that used the MNIST dataset have been updated to match the new interface.
> Creating a common protocol for image classification datasets, reworking MNIST to comply

- Benchmarks/Benchmark.swift
- Benchmarks/Models.swift
- Benchmarks/Models/ImageClassificationInference.swift
- Benchmarks/Models/ImageClassificationTraining.swift
- Benchmarks/README.md
- Benchmarks/main.swift
- Package.swift
This PR adds support for command-line argument parsing to the Benchmarks. The implementation is build upon Commander library and introduces two commands:
* `measure`. Starts a benchmarking of a single benchmark with given settings.
* `measure-all`. Run all benchmarks with default settings.
* `list-defaults`. See the list of all benchmarks and their default settings.
> Add initial support for command-line argument parsing

- Datasets/DatasetUtilities.swift
- Datasets/MNIST/MNIST.swift
Fixed typo in name of static property of type `URL` at [Datasets/DatasetUtilities.swift](https://github.com/tensorflow/swift-models/blob/master/Datasets/DatasetUtilities.swift)
> Fixed typo: curentWorkingDirectoryURL -> currentWorkingDirectoryURL

- Benchmarks/main.swift
- Datasets/CIFAR10/CIFAR10.swift
- Datasets/DatasetUtilities.swift
- Package.swift
- Support/Image.swift
- Support/Stderr.swift
Currently, we show log-style messages in stdout together with actual tool output (e.g., models print messages to show progress on loading the models). This makes it difficult to programmatically involve benchmarks cli from other tools. 
In this PR, we use stderr for logging-style messages instead. This is fairly standard convention in *nix world.
> Use stderr for logging messages

- Benchmarks/Models/ImageClassificationInference.swift
- Benchmarks/Models/ImageClassificationTraining.swift
- Examples/LeNet-MNIST/main.swift
- Models/ImageClassification/DenseNet121.swift
- Models/ImageClassification/LeNet-5.swift
The LeNet-5 and DenseNet models were previously set up with a softmax activation function on their last layer. This caused problems during training, because they were then used with `softmaxCrossEntropy(logits:labels:)`, leading to the softmax being applied twice. With this modification, the LeNet-5 model trained on MNIST matches the loss and accuracy of a reference Python TF 2.0 version of the same model at each step in training.
Additionally, the sum of the loss, rather than the average loss, was being reported for the LeNet-MNIST example. This has been corrected.
Finally, leftover TODO comments from a completed fix have been removed.
> Removing softmax as terminal activation function from two models

- MiniGo/Models/GoModel.swift
- Models/ImageClassification/DenseNet121.swift
- Models/ImageClassification/LeNet-5.swift
- Models/ImageClassification/ResNet50.swift
- Models/ImageClassification/ResNetV2.swift
- Models/ImageClassification/WideResNet.swift
Works around https://bugs.swift.org/browse/TF-1025 by specifying explicit activations on all the layers with default activations.
> work around duplicate definition of diff witness

- MiniGo/Models/GoModel.swift
- Models/ImageClassification/DenseNet121.swift
- Models/ImageClassification/LeNet-5.swift
- Models/ImageClassification/ResNet50.swift
- Models/ImageClassification/ResNetV2.swift
- Models/ImageClassification/WideResNet.swift
https://github.com/apple/swift/pull/28582 fixed https://bugs.swift.org/browse/TF-1025, making this workaround no longer necessary.
> Revert "work around duplicate definition of diff witness (#234)"

- Benchmarks/Models.swift
- Benchmarks/__init__.py
This PR adds support for minimal integration with [perfzero](https://github.com/tensorflow/benchmarks) benchmark runner.
Integration works by exposing a perfzero-compatible benchmark interface in python that instantiates underlying Swift benchmarks in a subprocess. Python integration can automatically pick up all benchmarks listed in `Models.swift` without any changes to the python code. 
After this PR one could use unmodified perfzero in combination with a custom [dockerfile](https://github.com/tensorflow/benchmarks/pull/440) to collect median benchmark running time (`wall_time` in perfzero terms). Currently we don't expose any other metrics but this can be added later on.
> Add support for minimal perfzero integration

- Datasets/CIFAR10/CIFAR10.swift
- Package.swift
- Tests/DatasetsTests/CIFAR10/CIFAR10Tests.swift
- Tests/DatasetsTests/CIFAR10/XCTestManifests.swift
- Tests/LinuxMain.swift
Removing using _Raw and use Tensor initializer instead to concatenate segments of datasets.
Details about removing _Raw see https://github.com/tensorflow/swift-models/issues/225.
> Remove _Raw from CIFAR10.swift

- Models/ImageClassification/ResNet50.swift
I had specified the block sizes for the various sizes of ResNet models based on Table 1 of ["Deep Residual Learning for Image Recognition"](https://arxiv.org/abs/1512.03385), however those block sizes did not account for the ResidualConvBlock before each ResidualIdentityBlockStack.
In order to still have each list of block counts match the published specification, I opted to subtract one from the input count at the point of forming the ResidualBasicBlockStack in order to account for the ResidualConvBlock before each.
After this change, the numbers and types of convolutions for each size should match reference implementations for the various sizes.
> Correcting block sizes for ResNet models

- Examples/LeNet-MNIST/main.swift
this is minor, but it's been driving me nuts for a little while.
originally the batchsize % dataset size == 0, so the logic worked.
but when moving to 128 as a batchsize, all the stats are now subtly off since the last batch size != 128.
we should find a better way to address this long term, or otherwise this bug will be copy-pasted everywhere. #241 is showing num_correct/512, when it should be /500, for example.  the two cifar demos use N * 10k % 100 so they work for now.
if there's a better way to calculate this, let me know!
> tweak mnist batchsize logic

- Benchmarks/__init__.py
This is a small change, driven purely by a presubmit linter warning with an internal build system.
> Minor edit to respond to Python linter warning

- Transformer/Model.swift
This PR switches off _Raw from Transformer/Model.swift by:
- using Tensor's concatenating initializer for concatenating tensors.
- using Tensor's bandPart operator for matrix bandPart operation.
More about removing _Raw: https://github.com/tensorflow/swift-models/issues/225
Able to run the model and got reasonable output after the change.
> Remove _Raw in Transformer/Model.swift

- Transformer/Operators.swift
This PR switches off _Raw from Transformer/Operators.swift by using matmul operator in Math.swift.
More about removing _Raw: #225
Able to run the model and got reasonable output after the change.
> Remove _Raw in Transformer/Operators.swift

- Models/ImageClassification/MobileNet.swift
- Tests/ImageClassificationTests/Inference.swift
Fixes #238.
Add MobileNet v1 model based on the [keras implementation](https://github.com/keras-team/keras-applications/blob/master/keras_applications/mobilenet.py).
Follow-on PRs will address creating a dataset (#237) and example that uses this model (#239).
> Add MobileNet v1

- Benchmarks/Benchmark.swift
- Benchmarks/BenchmarkResults.swift
- Benchmarks/Models/ImageClassificationInference.swift
- Benchmarks/Models/ImageClassificationTraining.swift
- Benchmarks/__init__.py
This commit adds support for two extra perfzero metrics:
* `exp_per_second` - number of examples per second, excluding warm-up.
* `avg_exp_per_second` - number of examples per second, including
warm-up.
> Add support for additional benchmark metrics

- Datasets/CIFAR10/CIFAR10.swift
- Datasets/MNIST/MNIST.swift
- Examples/LeNet-MNIST/main.swift
- Examples/ResNet-CIFAR10/main.swift
At present, the MNIST and CIFAR10 datasets download their binary files into the current working directory when used in example applications and tests. This can place these binary files in undesirable locations and fail in certain cases.
This pull request changes the default behavior for the MNIST and CIFAR10 datasets to instead download their binary files to `[system temporary directory]/MNIST` and `[system temporary directory]/CIFAR10`. If such a directory doesn't exist, it is created. Additionally, both datasets now have the capability of saving their binary files into a custom user-defined directory (previously, only the MNIST dataset supported this).
Also, the batch size on the ResNet training example was reduced in order to avoid memory exhaustion on smaller GPUs.
> Have datasets use a temporary directory for downloads by default

- docker/Dockerfile
Uses the docker image built in https://github.com/tensorflow/swift/pull/342.
This changes CI time from ~6min to ~5m30. Not as much speedup as I was hoping, but the code deduplication is good.
> speed up ci by using a prebuilt docker image

- Transformer/main.swift
This PR switches off _Raw from Transformer/main.swift by using Tensor categorical initializer.
More about removing _Raw: #225
Able to run the model and got reasonable output after the change.
> Use Tensor categorical initializer in Transformer/main.swift

- Benchmarks/PrintingStyle.swift
- Use `Array.reduce(into:)` for efficiency.
- Add `Array.variance` helper property.
- Minor style edits.
- Avoid explicit `self.` prefix when unnecessary.
---
[Verified correctness against NumPy](https://gist.github.com/dan-zheng/c46780a1068ad6345523b9f07c2bd776):
```swift
import Python
let np = Python.import("numpy")
for _ in 0..<100 {
let array = (0..<100).map { _ in Double.random(in: (-1000...1000)) }
let npArray = np.array(PythonObject(array))
let npStddev = np.std(npArray, ddof: 1)
print(array.standardDeviation)
print(npStddev)
assert(Bool(np.allclose(array.standardDeviation, npStddev))!)
}
```
> Minor changes to average/standard deviation calculation.

- Gym/Blackjack/main.swift
- Gym/CartPole/main.swift
- Gym/FrozenLake/main.swift
When we pull in the swift-models repository internally, we need to insert code to allow Python interoperability to work with the internal build system. These comments provide a hook to identify where that code should be inserted. They can be safely ignored for everything else.
> Adding comments as hooks for Python support when imported internally

- Datasets/CIFAR10/CIFAR10.swift
- Tests/DatasetsTests/CIFAR10/CIFAR10Tests.swift
This will provide flexibility to download dataset files from S4TF hosted binaries or any where else that the user can specify.
>  Enable user inputting source url while creating CIFAR10

- Datasets/CIFAR10/CIFAR10.swift
- Datasets/DatasetUtilities.swift
- Datasets/Imagenette/Imagenette.swift
- Datasets/MNIST/MNIST.swift
- Support/FileManagement.swift
This consolidates the downloading code in the MNIST and CIFAR-10 datasets so that they use the same core networking and unarchiving code. It also pulls out the downloading function as a free function for use outside of just the datasets.
> Restructuring dataset downloading code

- Benchmarks/__init__.py
The testcase class must actually inherit from perfzero-Benchmark class (which has the extra tpu kwarg). Also fix the cwd param
> Update swift models benchmark to be runnable continuously

- Datasets/MNIST/MNIST.swift
We should use the Google storage api link to load the MNIST dataset to avoid server overload. TFDS also uses this approach. (see [here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/mnist.py))
cc: @rickwierenga
> Update download link for MNIST

- Examples/ResNet-CIFAR10/main.swift
- Models/ImageClassification/ResNet.swift
- Tests/ImageClassificationTests/Inference.swift
This is an alternative to PR #281, in an attempt to restructure the ResNet model to simplify its overall structure and unify the 18 and 34 layer network architectures with the 50+ layer ones. It significantly reduces the overall lines of code when compared to the original model, lets one network be used for all sizes, and adds the flexibility of choosing both v1 and v1.5 variants.
The [implementation of ResNet within the Flax library](https://github.com/google-research/flax/blob/prerelease/examples/imagenet/models.py) was the source for the basic implementation structure, but this expands upon that by adding the basic blocks for ResNet 18 and 34, as well as support for both ResNet v1 and v1.5 variants.
A workaround is currently used to handle the differences between blocks that require …
> Restructuring the ResNet model to merge large and small variants, choose v1 vs. v1.5

- Gym/Blackjack/main.swift
- Gym/CartPole/main.swift
- Gym/FrozenLake/main.swift
This merely moves around some top-level constants and extensions in the Gym examples so that these examples can be cleanly imported internally. The function of the examples is preserved and functionality is not changed.
For context, we need to wrap the code below the `// Initialize Python` comments in a closure when importing internally at Google, and this simplifies the import process for us.
> Minor tweaks to the Gym models to allow for easier import internally

- Models/ImageClassification/ResNet.swift
Since there is no *4 expansion in the basic ResNets, the last number of filters is 512, not 2048, so that should be the number of inputs of the last dense layer. This PR fixes that.
> Fix the shape of the last dense layer in Resnet18 and ResNet34

- Models/Text/Architecture.swift
- Models/Text/BERTClassifier.swift
- Models/Text/CoLA.swift
- Models/Text/Evaluation.swift
- Models/Text/main.swift
There were a couple of issues that seem fixed now:
1. The sigmoid cross entropy loss was applied on logits of shape [B, 1] and labels of shape [B]. This forced a silent broadcast of logits to shape [B, B], which resulted in the loss not being informative for training.
2. The batch size was too small. I added a comment in the main script code explaining how batching works in my data pipelines.
3. This is a minor one but there is bug with how I was copying the prefetching iterator. This was a temporary solution but I just disabled prefetching for the dev and test sets so that the dev set is the same across runs.
This is not currently tuned but it's working. After ~20 steps MCC should be at about 0.28 and after ~200 steps it should be getting close to 0.50.
cc @dan-zheng
> Fixed BERT.

- Models/ImageClassification/ResNetV2.swift
- Tests/ImageClassificationTests/Inference.swift
This pull request adds the resnet V2 model that was trained internally on TPU to full accuracy adn removes the old legacy ResnetV2.swift file.
Tests have been updated to check each version of the model runs at inference.
> Add ResNet V2 and remove legacy file

- FastStyleTransfer/Utility/Resize.swift
This is needed to build on Windows.  Without this, the build would fail
as the expression would fail to typecheck.  Windows does not provide the
`round` macro, and requires that we explicitly use the typed macro for
the floating point operation (e.g. `roundf`, `roundl`, `roundll` instead
of `round`).
With this change it is possible to build the models on Windows.
> FastStyleTransfer: use `roundf` rather than `round`

- CMakeLists.txt
- DCGAN/CMakeLists.txt
- Datasets/CMakeLists.txt
- Examples/CMakeLists.txt
- Examples/Custom-CIFAR10/CMakeLists.txt
- Examples/LeNet-MNIST/CMakeLists.txt
- Examples/MobileNet-Imagenette/CMakeLists.txt
- Examples/ResNet-CIFAR10/CMakeLists.txt
- FastStyleTransfer/CMakeLists.txt
- GAN/CMakeLists.txt
- MiniGo/CMakeLists.txt
- Models/CMakeLists.txt
- Models/ImageClassification/CMakeLists.txt
- Support/CMakeLists.txt
- cmake/modules/SwiftSupport.cmake
This adds a CMake based build system for the models, enabling building
the models on platforms where swift-package-manager does not currently
function properly.
> build: add a CMake based build for the tensorflow-swift-models

- README.md
The explicit link against tensorflow has not been needed for a while.
Update the instructions accordingly.
> docs: update command

- Package.swift
While investigating example for VGG-Imagewoof I found that there is a line about how to execute it:
```sh
cd swift-models
swift run -c release VGG-Imagewoof
```
but actually no executable for that in `Package.swift`. So just a simple PR that adds it.
> Executable for VGG-Imagewoof

- Package.swift
Add a Transformers product to the manifest.  We had the local target,
but not an associated product previously.
> build: add Transformers product

- README.md
Point folks to use the tensorflow-xxx branches that correspond to their releases instead of the stable branch.
> Update Readme to get rid of references to the stable branch

- Transformer/encoder.py
When using this on Windows, Python would complain about the UTF-8
encoding in the file:
```
Non-ASCII character '\\xc2' in file ./Transformer\\encoder.py on line 23, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
Explicitly indicate the encoding in the file.
> Transformer: explicitly indicate encoding

- Support/CMakeLists.txt
Now that the CI builds are repaired, we are seeing the failure that was
originally missed.
> build: add missing sources to `ModelSupport`

- Transformer/Model.swift
This switches the `sqrt` to `sqrtf` which explicitly indicates the type.
This is required to enable building the transformer model on Windows.
> Transformer: use typed `sqrt`

- Datasets/DatasetUtilities.swift
there's probably a more elegant way to do this.
to trigger, try ```swift run TextModels``` on ubuntu.
> tweak unzip base dir on linux

- Datasets/CoLA/DataUtilities.swift
This ensures that we import FoundationNetworking whenever available.
This is needed when using SwiftFoundation on Darwin or building on
Windows.
> Datasets: import FoundationNetworking if possible

- Examples/BERT-CoLA/main.swift
`/tmp` is not the universal temporary directory.  Construct the path
in a more portable manner by using Foundation.  This also allows the
user to override the temporary path.
> BERT: remove hardcoded path assumption

- Models/Text/Attention.swift
- Models/Text/WeightDecayedAdam.swift
Use the typed math operations `powf`, `sqrtf`.  This is required to
ensure that we can build on Windows.
> Models: use explictly typed math operations (NFC)

- Transformer/Operators.swift
Fix Transformer linker error due to original/derivative declaration access level
mismatch: derivative is `@usableFromInline` but original is not.
Issue tracked at TF-1160.
Robust fix is TF-1099: require `@derivative` declarations to have same access
level as original declaration.
---
Unblocks https://github.com/tensorflow/swift-models/pull/324: add Transformer to CMake build.
> [AutoDiff] Fix Transformer CMake build linker error.

- README.md
Add some documentation on how to use the CMake based build and some of
the limitations of it.
> docs: document CMake support

- Examples/Regression-BostonHousing/main.swift
Use top-level `valueWithGradient` differential operator instead.
Method-style differential operators may be removed at any time, since
they were deprecated in the last release.
> Update deprecated method-style differential operator usage.

- Transformer/CMakeLists.txt
The transformer model uses `TextModels` but did not link against it,
which resulted in dependency issues.  This fixes the build on Windows.
> Transformer: link against `TextModels`

- Datasets/Imagenette/Imagenette.swift
PR #328 changed the core downloading function to automatically detect if a download destination was a file or directory. In order for a directory to be detected, it must be labeled as such when constructed, otherwise it will be treated as a file.
This fixes the Batcher pathway in Imagenette to download to a directory named Imagenette, not a file by that name. This should address issue #341.
> Minor correction to Imagenette Batcher downloading to indicate directory

- Models/ImageClassification/ResNet.swift
- Models/ImageClassification/ResNetV2.swift
As @pschuh mentioned to me, ResNet V2 did not have the zero init for the last BatchNorm layers, so this PR addresses that.
Also, now that https://github.com/tensorflow/swift-apis/pull/674 has landed in the nightlies, we can set the flag to not use bias in all the convolutional layers of both ResNet.
> Add zero init for last BN and don't use bias

- Package.swift
- Support/BijectiveDictionary.swift
- Support/CMakeLists.txt
- Tests/CMakeLists.txt
- Tests/LinuxMain.swift
- Tests/SupportTests/CMakeLists.txt
- Tests/SupportTests/SupportTests.swift
- Tests/SupportTests/XCTestManifests.swift
This allows us to map from key or value to their respective inverses.
As this is a common operation, place this into the Support module.
> Support: add a basic bi-directional mapping utility

- Models/Text/BERT.swift
When downloading the BERT pre-trained model, a directory may not be created (`Extracting archive... unzip:  cannot find or open /tmp/bert_models/bert/uncased_L-12_H-768_A-12.zip, ...
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory": ...`). 
So, in Colab, `bert` is not recognized as a folder in the `/tmp/` directory. This PR should fix it but there's still work for Xcode, as it throws a different error (see below). Your input, suggestions, any help would be welcome, especially for Xcode. I don't have extensive experience developing cool things with Swift, like the S4TF team.
@BradLarson The PR is based on your idea from https://github.com/tensorflow/swift-models/pull/342 (Thanks for fixing my #341 on Sunday!) - all …
> Indicate the BERT directory is labeled as such when downloading BERT

- Datasets/CIFAR10/CIFAR10.swift
- Tests/DatasetsTests/CIFAR10/CIFAR10Tests.swift
Addressing the request raised in #285 for adding an option to not normalize CIFAR10 images.
Added an optional argument to the function loadCIFARFile making normalization of CIFAR images optional. The default is to normalize the images so that the function is compatible with the previous versions of the code.
I haven't seen a PR for this even though the issue was more than a month older, so I did it myself.
Please review and let me know.
> Added an optional argument to the function loadCIFARFile making normalization of CIFAR images optional

- Autoencoder/main.swift
- DCGAN/main.swift
- GAN/main.swift
- Support/File.swift
- Support/Image.swift
Following changes have been proposed on `Image` structure:
1. Exposed `format` and `quality` argument labels to `saveImage(_:size:format:directory:name:quality:)` public function with default values of `format: .rgb` (because there's high probability the image will be RGB), `quality: 95`.
2. `size` is now used to resize the `tensor` instead of reshaping it. (There doesn't seem to be a requirement of reshaping image tensor.) But if it does seem important to community I think of renaming `size` to `newShape` for `reshaped(to:)` and `newSize` for resizing `tensor`.
3. `size` argument label is now `(Int?, Int?)` with default values `(nil, nil)`. If new argument value is provided during call then image tensor is resized otherwise original size is maintained.
4. `resized(to:)` instance method …
> Make `Image` more flexible

- CMakeLists.txt
- Support/CMakeLists.txt
- Transformer/CMakeLists.txt
Use CMake to fetch and build the dependencies.  This allows us to build
the demos without having to manually build the dependencies and alter
the flags.
> build: build swift-protobuf and SwiftWin32

- Support/Text/BytePairEncoder.swift
- Transformer/TransformerLoop.swift
- Import merge pairs from the correct file
- Fix merge pair functionality to operate on characters instead of tokens
- Use vocabulary inside BytePairEncoder rather than a local variable
- Minor cleanup in TransformerLoop
- Lint
> Transformer: merge pair fixes

- Support/Checkpoints/CheckpointReader.swift
The CRC verification within the CheckpointReader can severely slow down loading checkpoints in debug builds. It involves a tight loop that iterates over every byte in an often multi-megabyte binary representation of a tensor. Without the significant optimizations applied by the Swift compiler in release/optimized builds, this CRC function can be >120X slower in unoptimized builds. This can lead to minutes of loading time just to pull in a checkpoint within a debug build.
This adds the option to disable CRC verification on loading for the CheckpointReader, to be used in cases where you want to quickly iterate or test with an unoptimized build and know that you can rely on the fidelity of the checkpoint files.
Additionally, this performs some slight optimizations to the loop that allow the …
> Adding option to disable checkpoint data CRC on read, slight optimization of CRC

- Transformer/CMakeLists.txt
- Transformer/UI/Windows/main.swift
The second `main.swift` injected into the build is absolutely incorrect.
The `main.swift` from the target itself is the main file.
Import the additional TextModels, sort the link dependencies.
> Transformer: attempt to repair the Windows build

- CMakeLists.txt
There were some changes to CMake 3.17 which improved building for macOS.
Backport those as a workaround for the older CMake as a preparatory step
for adding the new macOS UI.
> build: backport some CMake fixes from 3.17

- Transformer/CMakeLists.txt
Although the manifest is unlikely to change, setup a dependency to
ensure that ninja is made aware that it needs to re-copy the file in the
case it does change.
> build: setup dependencies for the Windows build

- Transformer/CMakeLists.txt
We do not currently install any of the demos, remove the installation
for this particular demo.  We could introduce a new option to install
the demo programs, but given that they are demo programs, they are not
useful to install for persistence but more as a guide for getting
started.
> build: remove TransformerDemo from installation

- Datasets/TextUnsupervised/TextUnsupervised.swift
This adjusts the construction of the substring to build, even though it
is inefficient and uses a deprecated method:
```
SourceCache/swift-models/Datasets/TextUnsupervised/TextUnsupervised.swift:134:75: error: cannot convert value of type 'Int' to expected argument type 'String.Index'
rows[rows.count - 1].substring(to: rows[rows.count - 1].count - 2))
^
```
> Datasets: quick workaround to repair the macOS build

- Package.swift
- Transformer/CMakeLists.txt
- Transformer/UI/macOS/Info.plist
- Transformer/UI/macOS/main.swift
This is modelled after the Windows UI, and looks very similar.  This
actually helps demonstrate the point that the usage of the model is
extremely similar.  This sets an initial starting point for
improvements.
The biggest issue with the implementation currently is the `NSTextView`
does not update frequently enough resulting in the text appearing at the
end.
The differences from the Windows implementation include the fact that
`\n` does not need to be replaced with `\r\n`, the scrollview for the
textview needs to be constructed manually, and the coordinate system
uses a different origin.
> TransformerUI: add initial macOS UI

- Package.swift
saeta@saeta:~/src/swift-models$ swift test
Fetching https://github.com/apple/swift-protobuf.git
Fetching https://github.com/kylef/Spectre.git
Fetching https://github.com/kylef/Commander.git
Cloning https://github.com/apple/swift-protobuf.git
Resolving https://github.com/apple/swift-protobuf.git at 1.7.0
Cloning https://github.com/kylef/Commander.git
Resolving https://github.com/kylef/Commander.git at 0.9.1
Cloning https://github.com/kylef/Spectre.git
Resolving https://github.com/kylef/Spectre.git at 0.9.0
/usr/local/google/home/saeta/src/swift-models/Datasets/TextUnsupervised/TextUnsupervised.swift:134:34: warning: 'substring(to:)' is deprecated: Please use String slicing subscript with a 'partial range upto' operator.
rows[rows.count - 1].substring(to: rows[rows.count - …
> Fixes a compile error when building with a modern toolchain.

- Models/Text/GPT2/TransformerLM.swift
Add a conformance to `KeyPathIterable` for `TransformerML`.  This would
identified as missing when building the GPT2 model:
```
/Users/abdulras/SourceCache/swift-models/Examples/GPT2-WikiText2/main.swift:35:17: error: generic class 'Adam' requires that 'TransformerLM.TangentVector' conform to 'KeyPathIterable'
var optimizer = Adam(for: gpt.model, learningRate: 0.001)
^
TensorFlow.Adam:1:14: note: where 'Model.TangentVector' = 'TransformerLM.TangentVector'
public class Adam<Model> : Optimizer where Model : Differentiable, Model.TangentVector : ElementaryFunctions, Model.TangentVector : KeyPathIterable, Model.TangentVector : PointwiseMultiplicative, Model.TangentVector : VectorProtocol, Model.TangentVector.VectorSpaceScalar == Float {
^
```
> GPT2: make `TranformerLM` conform to `KeyPathIterable`

- Datasets/LanguageModelDataset.swift
- Datasets/TextUnsupervised/TextUnsupervised.swift
- Examples/GPT2-WikiText2/main.swift
- Tests/DatasetsTests/TextUnsupervised/TextUnsupervisedTests.swift
This PR adds a flag to optionally drop the last batch when it does not have `sequenceLength` elements. I think this will help fix #374 and in general be beneficial for training with fixed shapes on TPU.
> Adds the ability to drop the last batch

- Datasets/CoLA/CoLA.swift
- Datasets/CoLA/DataUtilities.swift
- Examples/BERT-CoLA/CoLATraining.swift
When training models on TPU, dynamic shape can cause recompilation overhead when input shape changes between steps. In Cola-BERT this can happen in Embedding layer where sequence length as well as batch size may vary if don't handle them carefully.
To prevent sequence length varying, we should pad sequences to maximum length. And we already did it by calling padAndBatch function [here](https://github.com/tensorflow/swift-models/blob/master/Datasets/CoLA/CoLA.swift#L168)
To prevent varying batch size we should drop the last batch where there aren't enough examples in there. And this PR is doing this.
Here is a brief explanation on how varying batch size happens: 
1. Our Cola data set has 8551 training examples and 1043 dev examples and we use batch 8 (1024/128). Apparently 8551=8x1068+7, …
> Drop last smaller batch in Cola-BERT

- Examples/GPT2-WikiText2/main.swift
With these numbers, this example can be run on smaller machines.
> Reduce batch size in GPT2

- Models/Text/GPT2/Operators.swift
This version conflicts with what is now in swift-apis and causes
materialization issues when used with x10.
> Remove custom gelu

- Benchmarks/main.swift
- Package.resolved
- Package.swift
This PR maintains the same interface that was defined with Commander,
so it is a NFC in a sense.
Resolves #354.
> Using ArgumentParser to parse CLI options for Benchmarks target.

- Transformer/README.md
Build instructions with absolute paths do not work for all installations.
Add a reminder to copy installation files after every VS update.
> GPT-2: Change absolute paths to relative in Windows build instructions

- FastStyleTransfer/Demo/ColabDemo.ipynb
As discussed in #410, Refactored the ColabDemo notebook with:
- appropriate indentation for conditional block
- moved `plt` declaration to newline
- grouped matplotlib related code under single comment.
Fixes #410 
There are few more suggestions I made in the issue, awaiting for your feedback on them.
> Refactored FastStyleTransfer ColabDemo

- Examples/MobileNet-Imagenette/README.md
Since this example uses Batcher, the warning about resource usage is no longer applicable.
> MobileNet: Remove resource usage warning

- Datasets/BostonHousing/BostonHousing.swift
- Datasets/CIFAR10/CIFAR10.swift
- Datasets/DatasetUtilities.swift
- Datasets/Imagenette/Imagenette.swift
- Datasets/Imagenette/Imagewoof.swift
- Datasets/MNIST/FashionMNIST.swift
- Datasets/MNIST/KuzushijiMNIST.swift
- Datasets/MNIST/MNIST.swift
- Tests/DatasetsTests/CIFAR10/CIFAR10Tests.swift
fixes #381
All datasets will be downloaded into "~/.s4tf/datasets" and not into a temporary directory like before.
> Preventing Datasets from re-downloading.

- Datasets/Imagenette/Imagenette.swift
- Datasets/Imagenette/Imagewoof.swift
- Support/Image.swift
Hello,
before this update, calling save on resized image would result to
```
Fatal error: image must be 3-dimensional[1,224,224,3]: file /Users/swiftninjas/s4tf/tensorflow-swift-apis/Sources/TensorFlow/Bindings/EagerExecution.swift, line 301
```
because `resized` actually returns a tensor of shape [1, size.0, size.1, channels] and this was saved as a tensor of image.
In loadImagenetteDirectory and loadImagewoofDirectory this was not an issue, because only scalars from the resized image were used. And in ImagenetteBatchers init, it was actually evaded by getting the first dimension from the tensor.
> Fix output shape of Image.resized

- Batcher/Batcher.swift
For the CIFAR10 and MNIST examples, the dataset is already loaded on the device, so these lines (which also fail with x10) will provoke a copy to the CPU then back on the accelerator, which will take unnecessary time.
For other datasets, there is probably no change doing it this way. This was the only part of `Tensorflow` used, so it should be okay to remove the import too.
> Remove device placement

- Datasets/BostonHousing/BostonHousing.swift
- Datasets/CIFAR10/CIFAR10.swift
- Models/Text/BERT.swift
At some point in the last day or so, the certificate for archive.ics.uci.edu expired, and as a result local tests that relied on downloading the BostonHousing dataset from that location are failing. The BostonHousing dataset has been changed to have its download location be on our GCS bucket for datasets and checkpoints. swift-format has been run over BostonHousing.swift.
We have seen some occasional download issues with the CIFAR-10 dataset, so that has also been changed to by default download from our GCS dataset bucket.
Finally, I forgot to update the RoBERTa checkpoint location to our GCS bucket when cleaning up some code there earlier, so I have done that now.
> Changing default download location for BostonHousing and CIFAR-10 datasets

- Benchmarks/Models.swift
- Benchmarks/Models/ImageClassificationInference.swift
- Benchmarks/Models/ResNetCIFAR10.swift
- Examples/ResNet-CIFAR10/main.swift
- Models/ImageClassification/ResNet.swift
In order to provide a head-to-head comparison with [the tf.keras ResNet56 on CIFAR-10 benchmark model](https://github.com/tensorflow/models/blob/master/official/benchmark/models/resnet_cifar_model.py), this adds a ResNet56 model depth per [the original paper](https://arxiv.org/pdf/1512.03385.pdf) and configures a benchmark of training it on the CIFAR-10 dataset. It also tweaks the ResNet-CIFAR10 example to use the ResNet56 architecture on CIFAR-10, a more common choice for that dataset.
> Adding a ResNet56-CIFAR10 benchmark

- Support/STBImage/CMakeLists.txt
Mark the library to be built as position independent code.
> STBImage: build with `-fPIC`

- Datasets/CIFAR10/CIFAR10.swift
- Tests/DatasetsTests/CIFAR10/CIFAR10Tests.swift
The normalized values in CIFAR10 look off.  `mean: [0.0279,  0.1167,  0.1801]` and `std: [1.078, 1.086, 1.162]`.  The code to reproduce in Colab is below.
This pull:
- tests that normalized mean is near [0, 0, 0] and std is near [1, 1, 1]
- updates the mean and std used to normalise so the new test passes
import Datasets
import TensorFlow
import Foundation
let dataset = CIFAR10(batchSize: 50000) // normalizes by default
for batch in dataset.training.sequenced() {
let images = Tensor<Double>(batch.first)
let mom = images.moments(squeezingAxes: [0, 1, 2])
print("mean: \(mom.mean)")
print("std: \(sqrt(mom.variance))")
}
> add test and fix cifar10 normalization values

- Support/FileManagement.swift
A minor bug rendered the extension filtering ineffective as the function repeatedly checks only the first file of the directory.
> Fixed collectURLs extensions filtering

- Gym/CartPole/main.swift
- Gym/FrozenLake/main.swift
- Tests/CheckpointTests/CheckpointIndexReaderTests.swift
- Tests/CheckpointTests/CheckpointReaderTests.swift
- Tests/CheckpointTests/SnappyDecompressionTests.swift
- Tests/SupportTests/ImageTests.swift
In anticipation of [SE-0274](https://github.com/apple/swift-evolution/blob/master/proposals/0274-magic-file.md), this converts our use of `#file` to `#filePath`. We had been using the full path to point to test and other local files, which will stop functioning when `#file` produces an abbreviated file name.
We have access to `#filePath` within our toolchain, so we should be able to implement this now without impact to our targets here.
> Convert #file -> #filePath

- Datasets/MNIST/KuzushijiMNIST.swift
The server hosting the original KMNIST dataset archives went offline today, triggering test failures, so we've hosted a copy of these archives on GCS. This updates the archive URLs to point to the new locations on our GCS bucket.
> Point KMNIST at GCS-hosted archives

- Benchmarks/Benchmark.swift
- Benchmarks/BenchmarkModel.swift
- Benchmarks/BenchmarkResults.swift
- Benchmarks/BenchmarkSettings.swift
- Benchmarks/BenchmarkVariety.swift
- Benchmarks/Models.swift
- Benchmarks/Models/ImageClassificationInference.swift
- Benchmarks/Models/ImageClassificationTraining.swift
- Benchmarks/Models/LeNetMnist.swift
- Benchmarks/Models/ResNetCIFAR10.swift
- Benchmarks/Models/SyntheticImageDataset.swift
- Benchmarks/PrintingStyle.swift
- Benchmarks/__init__.py
- Benchmarks/main.swift
- Package.swift
In order to better align the training and inference throughput benchmarks with the ones used for tf.keras, I've converted the training benchmarks to use batches as the fundamental unit of measure, not epochs. I've also introduced a specified warmup period (defaulting to one batch) before batches are counted for throughput.
Logging has been improved, so that you get statistics on examples / second, warmup time, and step time right at the command line. This includes minimum, maximum, and standard deviation so that anomalous outliers can be detected.
Internal setting values have been switched from using magic constants to relying on optionals early and then materializing these into concrete values closer to where options are specified. This should hopefully catch problematic cases earlier in …
> Restructuring benchmarks to be batch-based in training, use warmup

- Benchmarks/__init__.py
In PR #444, I incorrectly left off some changes to the PerfZero Python setup files in order to match to the new benchmark metrics in that pull request. This corrects that omission, and should enable PerfZero benchmarks to integrate cleanly with the new Swift benchmarks.
> Correcting PerfZero benchmarks for new architecture

- docker/Dockerfile
https://github.com/apple/swift/pull/31158 makes it so that all of our toolchains include x10. Therefore, I want to change our automated build to stop publishing toolchains named "-x10-". This prepares for this change.
> remove x10 from toolchain url

- docker/Dockerfile
Update Dockerfile to use the CUDA toolchain instead of regular one
This is consistent with swift-apis.
> Update Dockerfile to use the CUDA toolchain instead of regular one

- Batcher/Backend.swift
- Batcher/Batcher.swift
- Batcher/Collatable.swift
- Datasets/COCO/COCODataset.swift
- Datasets/ObjectDetectionDataset.swift
- Datasets/TensorPair.swift
- pix2pix/Dataset.swift
In order to merge the [epochs PR](https://github.com/tensorflow/swift-apis/pull/864), we need to temporarily rename `Collatable` and `concurrentMap` to avoid conflicts with the same struct/extension in Epochs.
This PR underscores them, we can undo that in the applications once the epochs PR is merged and in the nightlies.
> Rename to merge Epochs

- CycleGAN/main.swift
`String` has no member called `length`.
Use `String.isEmpty` instead.
---
Fixes `swift build` (on macOS):
```console
$ swift build
swift-models/CycleGAN/main.swift:28:24: error: value of type 'String' has no member 'length'
if options.datasetPath.length != 0 {
~~~~~~~~~~~~~~~~~~~ ^~~~~~
```
Confirmed that `swift run CycleGAN` works.
> Fix CycleGAN build error.

- CycleGAN/CLI.swift
- CycleGAN/main.swift
- pix2pix/CLI.swift
- pix2pix/main.swift
Use `String?` instead of `String` with default empty string to parse
CycleGAN and pix2pix command line arguments.
Fiollow-up to https://github.com/tensorflow/swift-models/pull/460.
Confirmed that `swift run CycleGAN` and `swift run pix2pix` continue to work.
> Use `String?` instead of `String` in CLIs.

- Benchmarks/Benchmark.swift
- Benchmarks/BenchmarkSettings.swift
- Benchmarks/Models/ImageClassificationInference.swift
- Benchmarks/Models/ImageClassificationTraining.swift
- Benchmarks/Models/LeNetMnist.swift
- Benchmarks/Models/ResNetCIFAR10.swift
- Benchmarks/PrintingStyle.swift
- Benchmarks/__init__.py
- Benchmarks/main.swift
In order to provide benchmarks for the new x10 backend, in addition to the existing eager backend, this adds the `--x10` and `--eager` options to the Benchmarks target. These options switch between using the X10 and eager backends, respectively, and support has been added within the image classification inference and training benchmarks to support X10 in parallel with the default eager execution.
For now, we're using the first two batches as a warmup period, instead of just the first batch (as is done for the other PerfZero benchmarks), due to an extra recompilation we're experiencing in the second batch. Once that extra recompilation is removed, we'll switch back to a single batch for warmup.
Additionally, to work around some caching artifacts we're seeing with batched data, I'm doing an …
> Add eager / X10 backend selection to the benchmarks

- Benchmarks/__init__.py
I accidentally forgot to split the argument for the `warmupBatches` in PR #468, and only ran the Docker tests on the commit just before that, so this slipped through. This re-enables our benchmarks with correct arguments.
> Quick fix for a bad PerfZero argument

- Models/ImageClassification/ShuffleNetV2.swift
Change `inputChannels` from variable to constant to resolve compiler warning:
```
Models/ImageClassification/ShuffleNetV2.swift:73:13: warning: variable 'inputChannels' was never mutated; consider changing to 'let' constant
```
> [ShuffleNetV2] Resolve warning about non-mutating var

- Datasets/CoLA/CoLA.swift
- Support/Text/TextBatch.swift
This is the first step toward using Epochs to load the COLA dataset. The changes are:
- make `TextBatch` conform to `Collatable` (this will be trivial once derived conformance is implemented in master);
- use `let` instead of `var` inside `TextBatch` since we don't need to mutate them;
- make the padding function a method on `Collection` of `TextBatch` (with the same name as what is in Epochs for consistence).
> Use Collatable for TextBatch

- Models/ImageClassification/EfficientNet.swift
- Models/ImageClassification/MobileNetV2.swift
- Models/ImageClassification/MobileNetV3.swift
- Models/ImageClassification/VGG.swift
- Models/Spatiotemporal/C3D.swift
Due to our use of `softmaxCrossEntropy(logits:labels:)` within training and inference for our image classification models, they should not contain a terminal softmax activation function within the model itself. In PR #232, we had removed some of these from existing classification models, and this PR removes softmax from newly contributed models since that time.
Thanks go to Peter Jung for pointing this out.
> Removing softmax activation within remaining classification models

- Benchmarks/Models/ResNetCIFAR10.swift
- Datasets/CIFAR10/CIFAR10.swift
- Datasets/CIFAR10/OldCIFAR10.swift
- Datasets/CMakeLists.txt
- Datasets/ImageClassificationDataset.swift
- Examples/Custom-CIFAR10/main.swift
- Examples/ResNet-CIFAR10/main.swift
- Support/CMakeLists.txt
- Support/LabeledData.swift
- Tests/DatasetsTests/CIFAR10/CIFAR10Tests.swift
This PR starts the work of removing `Batcher` and use `Epochs` instead.
To avoid one gigantic PR, I have created  new protocol named `ImageClassificationData` that I use and kept the old cifar model in OldCifar10 (to use it in the benchmarks). The protocol `ImageClassificationData` can be renamed once everything is done and the current `ImageClassificationDataset` is removed.
The OldCifar10 file can be removed when MNIST and the benchmarks have been converted to use Epochs.
New with this implementation:
- the shuffle of the training set can be seeded;
- the pixel values of the tensors are always scaled to [0, 1] even if normalize is false;
- the tensors are created on the fly from the raw UInt8 data to avoid launching several kernels of Tf-runtime
> Use Epochs to load CIFAR10

- Autoencoder/Autoencoder1D/main.swift
- Autoencoder/Autoencoder2D/main.swift
- Autoencoder/VAE1D/main.swift
- Benchmarks/Models/LeNetMnist.swift
- DCGAN/main.swift
- Datasets/CIFAR10/CIFAR10.swift
- Datasets/CMakeLists.txt
- Datasets/MNIST/FashionMNIST.swift
- Datasets/MNIST/KuzushijiMNIST.swift
- Datasets/MNIST/MNIST.swift
- Datasets/MNIST/MNISTDatasetHandler.swift
- Datasets/MNIST/OldFashionMNIST.swift
- Datasets/MNIST/OldKuzushijiMNIST.swift
- Datasets/MNIST/OldMNIST.swift
- Datasets/MNIST/OldMNISTDatasetHandler.swift
- Examples/LeNet-MNIST/main.swift
- GAN/main.swift
- Tests/DatasetsTests/CIFAR10/CIFAR10Tests.swift
- Tests/DatasetsTests/MNIST/MNISTTests.swift
Followup to #495 
This PR convert the MNIST datasets to the Epochs API, while keeping the old ones that are used in Benchmarks, autoencoder and GAN examples. The next follow-up will convert Benchmarks to use the new CIFAR10 and new MNIST datasets, then I'll adapt the code of Autoencoders and GAN examples to be able to remove those OldFoo files.
> Convert MNIST to Epochs

- Datasets/TextUnsupervised/TextUnsupervised.swift
Text encoding with Byte Pair Encoder has O(N*N) time complexity https://github.com/tensorflow/swift-models/blob/master/Support/Text/BytePairEncoder.swift#L101. Encoding for full WikiText2 training and testing dataset can take ~100 minutes. 
We wanted to make the cache optional where if the encoded text provided then load them directly.
> Load encoded file if BPE is nil in TextUnsupervised

- Datasets/TextUnsupervised/TextUnsupervised.swift
- Tests/DatasetsTests/TextUnsupervised/TextUnsupervisedTests.swift
#490 removed the requirement to provide a byte pair encoder when initializing `TextUnsupervised`. This init function was essentially a placeholder and is no longer necessary, so remove it.
> Remove unnecessary init in TextUnsupervised

- Tests/TextTests/WordSegmentationTests/ProbeLayers.swift
- Tests/TextTests/WordSegmentationTests/WordSegmentationTests.swift
- Tests/TextTests/XCTestManifests.swift
This makes it easy to run all WordSeg tests via `swift test --filter WordSeg`.
> Prepend all WordSeg tests with "WordSeg".

- Models/Text/WordSeg/Model.swift
- Inline stale workaround functions.
- These functions were added to work around differentiation crashes.
These crashes are no longer reproducible.
- Remove duplicate derivative for `RecurrentLayer.callAsFunction(_:initialState:)`.
- This derivative wrt `(self, inputs, initialState)` was [upstreamed to
tensorflow/swift-apis](https://github.com/tensorflow/swift-apis/blob/763fa17a91bdc6d241d123a923dbc0ea1229d808/Sources/TensorFlow/Layers/Recurrent.swift#L380-L422).
> Fix some WordSeg AutoDiff todos.

- Models/Text/WordSeg/Model.swift
Use in-place array element updates instead of functional element updates.
This should improve performance.
An `Array.update(at:to:)` helper method is needed until idiomatic array element
updates (`array[index] = newValue`) can be differentiated: TF-1277.
> [WordSeg] Use in-place array element updates.

- Models/Text/WordSeg/Lattice.swift
- Models/Text/WordSeg/Model.swift
Remove dummy `Tensor<Float>` argument from `Lattice.init(count:)`.
It was a workaround for an activity analysis bug, no longer reproducible.
> [WordSeg] Remove autodiff workaround.

- Models/Text/WordSeg/Model.swift
Clarify autodiff workarounds related to TF-433: autodiff does not yet support
non-active throwing/rethrowing functions like `Array.map` and `Bool.&&`.
> [WordSeg] Clarify autodiff workarounds.

- Models/Text/WordSeg/Lattice.swift
- Models/Text/WordSeg/Model.swift
Update lattice nodes by creating and mutating a local `var` variable, rather
than initializing a new `let` variable. This shortens the code.
Reference TF-1193: support derivative registration for accessors.
`@derivative(of: Lattice.subscript.set)` enables further code cleanup.
Add "cleanup" comments showing ideal final code.
> [WordSeg] Clean up lattice node updates.

- Models/Text/WordSeg/Model.swift
- Tests/TextTests/WordSegmentationTests/ProbeLayers.swift
Spell out SNLM stored properties:
- `embEnc` -> `encoderEmbedding`
- `lstmEnc` -> `encoderLSTM`
- `embDec` -> `decoderEmbedding`
- `lstmDec` -> `decoderLSTM`
- `denseDec` -> `decoderDense`
- `drop` -> `dropout`
> [WordSeg] Use idiomatic SNLM stored property names.

- Models/Text/WordSeg/Lattice.swift
- Models/Text/WordSeg/SemiRing.swift
Rewrite `semiRingSum(_:)` to `Array.sum()`, which is more idiomatic.
> [WordSeg] Minor semiring sum cleanup.

- Autoencoder/Autoencoder1D/main.swift
This PR addresses one of the issues [here](https://github.com/tensorflow/swift-models/issues/511).
1. Switch OldFashionMNIST to FashionMNIST
2. Keep the behavior of saving one pair of image(input and output pair) in each epoch.
3. Change to printing loss each epoch from previously each testing batch
> Switch off OldFashionMNIST in Autoencoder1D

- Examples/WordSeg/main.swift
Remove fixed number of training epochs. Instead, continue training until validation loss has not improved for 5 consecutive epochs.
> [WordSeg] Train until loss stops improving.

- Models/Text/GPT2/GPT2.swift
GPT2 initializer tries to load parameters by directly referencing `Transformer` directory under temporary directory, which happens to be where CheckpointReader keeps those files if modelName is `Transformer`. This works if there is only one checkpoint on the system, for example 117M. Using GPT2 with other checkpoints will break with shape errors.
```
Fatal error: Input to reshape is a tensor with 5120 values, but the requested shape has 5100: file /Users/swiftninjas/s4tf/tensorflow-swift-apis/Sources/TensorFlow/Bindings/EagerExecution.swift, line 301
```
This change uses the directory name as part of the modelName parameter of CheckpointReader, for example: GPT2-117M, GPT2-345M to avoid mixing files. It also uses CheckpointReader's localCheckpointLocation to get the directory of the …
> Loading multiple GPT2 checkpoints on same computer.

- Examples/GPT2-Inference/main.swift
- Models/Text/GPT2/GPT2.swift
Every once in a while, GPT2-Inference will crash with this error:
```
Illegal instruction (core dumped)
```
This change adds unwrapping protection in case something goes wrong during generation.
> [GPT2] Add generation unwrapping protection

- Examples/NeuMF-MovieLens/main.swift
- Models/Recommendation/NeuMF.swift
* Generalized the model by building the layers in an array and processing through `differentiableReduce()`
* Using more descriptive names for model parameters
* Updated NeuMF example to work with the new parameter names
> In the Neural Collaborative Filtering model, generalize to arbitrary layers and improve parameters (#474)

- Examples/GPT2-Inference/main.swift
- Models/Text/GPT2/GPT2.swift
- Support/Text/BytePairEncoder.swift
This is a temporary patch to prevent crashes caused by a bug in `BytePairEncoder` support for multibyte unicode scalars, described in #385
> [GPT2] Capture an error on unicode support bug

- Models/Text/GPT2/TransformerLM.swift
With the small pre-trained model, zero-shot with WikiText2 is supposed to get 29.41 ppl, whereas what we get is as high as e^10. It turns out that the major cause is a bug in the model: it applies QKV split after head split. This PR fixes this. (Note: there is another smaller cause from encoding where we find 1.35% tokens are improperly encoded.)
> GPT2 fix: should split QKV first then head

- Datasets/WordSeg/WordSegDataset.swift
- Support/FileManagement.swift
Zipped datasets currently use the local `unzip` command to decompress. The default options for `unzip` log out the individual file names in the archive to standard out. When running benchmarks that expect a JSON output, this corrupts the resulting command-line output. This makes a quick change to silence that output during unzipping.
The WordSeg dataset was also being downloaded to a different location than the other datasets, so that has been aligned with the others.
> Suppress output from unzipping datasets

- Models/Text/GPT2/PythonCheckpointReader.swift
- Models/Text/GPT2/TransformerLM.swift
This PR resolves issue https://github.com/tensorflow/swift-models/issues/104.
hugging face model for reference: https://github.com/huggingface/transformers/blob/2c1ebb8b507c19c75af5084b6c73e0b003c9eda6/src/transformers/modeling_gpt2.py
and dropout possibility settings:
https://github.com/huggingface/transformers/blob/2c1ebb8b507c19c75af5084b6c73e0b003c9eda6/src/transformers/configuration_gpt2.py#L122
> Make GPT2 Dropout aligned with huggingface

- Benchmarks/Models/WordSeg.swift
- Examples/WordSeg/main.swift
- Models/Text/WordSeg/Lattice.swift
- Models/Text/WordSeg/Model.swift
- Models/Text/WordSeg/SemiRing.swift
- Package.resolved
- Tests/TextTests/WordSegmentationTests/ExampleData.swift
- Tests/TextTests/WordSegmentationTests/ProbeLayers.swift
- Tests/TextTests/WordSegmentationTests/SemiRing.swift
After profiling, it appears that we're creating a lot of small Tensors in the last steps of `buildLattice()`, where those calculations might better be performed using scalars on the host side. This PR therefore effectively rolls back portions of PR #535 to return to the use of scalars in many places.
Benchmarks before this change on a GTX 1080-equipped Ubuntu system:
WordSeg_score_4: 314 ms / step
WordSeg_score_and_gradient_4: 2801 ms / step
After:
WordSeg_score_4: 132 ms / step
WordSeg_score_and_gradient_4: 1246 ms / step
> Convert portions of WordSeg to use scalars instead of Tensors

- Examples/WordSeg/README.md
Adds a link to the document @sgugger created that describes the WordSeg paper in detail.
Also adds a validation set to sample commands for viewing inference results during training.
> [WordSeg] Add link to explanation doc

- Examples/LeNet-MNIST/main.swift
First of many PRs for #514.
Been busy with a few things lately hence the hiatus. Played around with X10 the last couple of days and I am really exited about the future of the S4TF project. Great work
> Convert LeNet-MNIST example to X10

- docker/Dockerfile
We're experiencing intermittent SSL errors when trying to download the Swift nightly for CI builds. Added a retry of the curl command to the Dockerfile, which seems to defend against this and make CI more reliable.
> Add a retry to the Swift download in the Dockerfile

- Autoencoder/Autoencoder1D/main.swift
- Autoencoder/Autoencoder2D/main.swift
- Benchmarks/Models/ImageClassificationInference.swift
- Benchmarks/Models/ImageClassificationTraining.swift
- Benchmarks/Models/SyntheticImageDataset.swift
- Datasets/CIFAR10/CIFAR10.swift
- Datasets/MNIST/FashionMNIST.swift
- Datasets/MNIST/KuzushijiMNIST.swift
- Datasets/MNIST/MNIST.swift
- Datasets/TextUnsupervised/TextUnsupervised.swift
- Examples/GPT2-WikiText2/main.swift
- Package.swift
There were several left over references to Batcher in targets that no longer needed that older API. These have been removed.
> Remove outdated references to Batcher

- Datasets/ImageSegmentationDataset.swift
- Datasets/OxfordIIITPets/OxfordIIITPets.swift
- Tests/DatasetsTests/OxfordIIITPets/OxfordIIITPetsTests.swift
Continuing the process described in issue #592, this migrates the OxfordIIITPets dataset and tests from Batcher to the new Epochs API.
> Migrating OxfordIIITPets dataset to Epochs

- Datasets/CMakeLists.txt
- Datasets/COCO/COCO.swift
- Datasets/COCO/COCODataset.swift
- Datasets/COCO/COCOVariant.swift
- Datasets/LanguageModelDataset.swift
- Datasets/ObjectDetectionDataset.swift
- Datasets/TensorPair.swift
- Package.swift
- Tests/DatasetsTests/COCO/COCODatasetTests.swift
In response to part of issue #592, this migrates the COCO dataset to the Epochs API. Further cleanup might be required to better align the lazy object detection pipeline with Epochs and its new capabilities, but this provides the same functionality as before and removes deprecation warnings.
As this was the last use of TensorPair's _Collatable functionality, that has been removed. Batcher dependencies have also been removed from the Datasets module.
Additionally, copyright headers were missing from several files and have been added.
> Migrating the COCO dataset to Epochs

- Examples/BERT-CoLA/main.swift
There is an `epochCount` variable but actual number of epochs is hard-coded. Just a small fix.
> Fix epoch count in bert cola example

- Examples/WordSeg/CMakeLists.txt
- Examples/WordSeg/README.md
- Examples/WordSeg/WordSegCommand.swift
- Examples/WordSeg/WordSegSettings.swift
- Examples/WordSeg/main.swift
- Package.swift
Fixes #601 
Adds names to command-line arguments using `ArgumentParser`.
Updates README with new commands and how to view all available arguments with defaults.
Scopes helper functions as `fileprivate`.
> [WordSeg]: Add named arguments with defaults

- Benchmarks/Models/ImageClassificationInference.swift
- Benchmarks/Models/ImageClassificationTraining.swift
- Benchmarks/Models/WordSeg.swift
Larger X10 models occasionally cause crashes when run in our benchmarks, but these crashes were only occurring at the very end of the benchmark. Tracking this down, it appears to be due to X10 (at least on GPU) executing traces asynchronously, leading to them running slightly after the point that the model and optimizer have gone out of scope. Inserting a synchronous barrier that blocks until execution is finished prevents these crashes.
This is inserted immediately before the returns of the timing values, because I found that this is the only location that reliably prevents crashes. Placing this barrier in a `defer` doesn't achieve the desired results, and the barrier must be within the benchmark function where the model and optimizer are allocated.
This addresses issue #528, but a more …
> Workaround to prevent X10 crashes during benchmarks

- Datasets/CoLA/CoLA.swift
- Examples/BERT-CoLA/main.swift
Ran into "ambiguous for type lookup in this context" error when importing Datasets module while redefining the alias locally. This change constrain it inside CoLA struct to prevent the conflict.
> Move typealias LabeledTextBatch into struct CoLA

- FastStyleTransfer/Layers/Helpers.swift
- Models/ImageClassification/ShuffleNetV2.swift
- Models/Text/GPT2/TransformerLM.swift
- pix2pix/Layers.swift
Associated type inference behavior was changed in https://github.com/apple/swift/pull/32578:
derived conformances are now attempted before associated type inference.
This broke `ParameterlessLayer`, which relied on a
`TangentVector == EmptyTangentVector` same-type constraint to set a
default `TangentVector` type witness for conforming types.
Add explicit `TangentVector` type witnesses to
`ParameterlessLayer`-conforming types to fix this regression.
This workaround is forward- and backward-compatible, but makes code more
verbose.
Related `tensorflow/swift-apis` change: https://github.com/tensorflow/swift-apis/pull/1034
---
Fixes build errors from the [2020-06-30 `master -> tensorflow` merge](https://github.com/apple/swift/pull/32623):
<details>
``` …
```
> Fix `ParameterlessLayer` conformances.

- Tests/TextTests/WordSegmentationTests/ProbeLayers.swift
Lingering print statements clutter up the logs. No need to output details of successful tests.
> Remove print statements from tests

- Benchmarks/Models/LeNetMNIST.swift
- Benchmarks/Models/ResNetCIFAR10.swift
- Benchmarks/Models/ResNetImageNet.swift
- Benchmarks/__init__.py
This change addresses accidental change for startup_time measurement when run within perfzero.
Instead of overriding warmup iterations in python wrapper, we rely on better per-suite defaults.
> Don't override --warmup-iterations in perfzero integration

- TrainingLoop/TrainingProgress.swift
The use of ANSI command codes wasn't allowing the progress bar to animate properly in Colab. By replacing those codes with a simpler use of carriage returns, the progress bar now animates properly in Colab and on the command line.
> Making animated training progress bar compatible with Colab

- Benchmarks/Layers/DefaultInit.swift
- Benchmarks/Layers/DenseNet.swift
- Benchmarks/Layers/Dimensions.swift
- Benchmarks/Layers/EfficientNet.swift
- Benchmarks/Layers/LayerSuite.swift
- Benchmarks/Layers/LayerSuites.swift
- Benchmarks/Layers/LeNet.swift
- Benchmarks/Layers/MobileNetV1.swift
- Benchmarks/Layers/MobileNetV2.swift
- Benchmarks/Layers/MobileNetV3.swift
- Benchmarks/Layers/ResNet.swift
- Benchmarks/Layers/ResNetV2.swift
- Benchmarks/Layers/ShuffleNetV2.swift
- Benchmarks/Layers/SqueezeNet.swift
- Benchmarks/Layers/VGG.swift
- Benchmarks/Layers/WideResNet.swift
- Benchmarks/Models/ModelSuites.swift
- Benchmarks/Suites.swift
This PR builds upon upon #612 and adds infra for fine-grain benchmarks for arbitrary `Layer<Float>`:
* Performance of the forward pass
* Performance of the gradient + forward pass 
Primary objective of these benchmarks is to evaluate performance of autodiff code generation. The difference between two benchmarks is the time taken by backwards pass that we want to improve upon.
The PR includes all of our image classification models, and all of their variants on common input sizes (Mnist, Cifar, ImageNet).
I also hand-picked a common largest batch size which works for all of the image classification models in eager mode on V100. it's relatively small but it allows us to compare benchmarks at the same batch size.
> Add fine-grain layer benchmarks

- TrainingLoop/TrainingStatistics.swift
Currently I think accuracy is averaged across all epochs and across training and inference runs.  Reseting accuracy statistics to `nil` at the start of training and validation makes them per epoch and resets the totals between training and inference.  This mimics how average loss works.
Some MNIST results below show how prior to this change the accuracy is low for all epochs because of averaging across epochs.  It also shows that the training and validation accuracy before change are always similar because the average is across both.  After this change initial validation accuracy is higher but eventually the model overfits and validation accuracy is below training accuracy.  
Output from `swift run -c release LeNet-MNIST` after these changes:
Epoch 1/12
468/468 …
> reset accuracy statistics each epoch and between training and validation

- BenchmarksCore/BenchmarkArguments.swift
- BenchmarksCore/BenchmarkSettings.swift
- BenchmarksCore/Models/WordSeg.swift
Adds `datasetFilePath` argument and passes the value to WordSeg benchmarks. This is useful for specifying file locations other than the default download location.
> Add `datasetFilePath` argument for benchmarks

- Package.swift
Since 0.2.0 contains some incompatibilities, let's update sooner rather than later.
This matches swift-benchmark's [recent update](https://github.com/google/swift-benchmark/pull/65).
> Bump swift-argument-parser to 0.2.0

- BenchmarksCore/BenchmarkArguments.swift
Fixes #636 
Removes camelCase overrides for benchmark arguments, using the [swift-argument-parser](https://github.com/apple/swift-argument-parser) default provided by [swift-benchmark](https://github.com/google/swift-benchmark). This changes the `batchSize` argument to `batch-size` and `datasetFilePath` to `dataset-file-path`.
> Remove camelCase override

- Examples/BERT-CoLA/main.swift
- Models/Text/BERT.swift
Clone #534 
The build issues have been fixed.
The `electra-small` model is not supported due to a different hidden size than the formula permits, I mentioned this issue in #534 as well.
> Although the hidden_size = embedding_size generally for Electra, but in the case of electra_small, the embedding size is 128 while the hidden size is 256, any idea how I could solve in that particular case?
Other than that, build passes.
> Add support for electra

- Datasets/CoLA/CoLA.swift
- Examples/BERT-CoLA/main.swift
- Support/Text/TextBatch.swift
Eliminates device copying in the example code by allowing users to specify a device to load CoLA onto.
> Shift x10 transformations from the BERT-CoLA example into the CoLA dataset

- Package.swift
It seems that the package name in `Package.swift` needs to match the github repo name to be able to depend on the libraries that this exports.
Here is how I am trying to depend on the libraries:
```swift
// swift-tools-version:5.3
import PackageDescription
let package = Package(
name: "DeepBeeTracking",
products: [
.executable(name: "TrainUNet", targets: ["TrainUNet"])
],
dependencies: [
.package(url: "https://github.com/tensorflow/swift-models.git", .branch("master")),
],
targets: [
.target(
name: "DeepBeeTrackingDatasets",
dependencies: [
.product(name: "Datasets", package: "TensorFlowDatasets"),
.product(name: "ModelSupport", package: "TensorFlowDatasets"),
]),
.target(
name: "TrainUNet",
dependencies: ["DeepBeeTrackingDatasets"]),
]
))
```
This produces the error:
``` …
```
> change Package.swift package name

- Package.swift
Swift-Benchmark currently has an unstable API. This change pins
Swift-Benchmark to an explicit revision to ensure stable builds.
> Pin swift-benchmark to a specific revision.

- Models/Text/WordSeg/Model.swift
The pullback of `Array.update(at:to:)` resets `dSelf.base[index]` to a zero value.
For correctness, it should use the value of `self[index].zeroTangentVector` before
the update occurs, not `dElement.zeroTangentVector`.
---
Fixes `WordSegProbeLayerTests.testProbeEncoder` after the `2020-07-28 master -> merge`.
Previously, the test passed due to an incorrect definition of `Array.TangentVector.zeroTangentVectorInitializer`, which was fixed in https://github.com/apple/swift/pull/32948.
> [WordSeg] Fix pullback for `Array.update(at:to:)`.

- BenchmarksCore/BenchmarkArguments.swift
- BenchmarksCore/BenchmarkSettings.swift
Adds 3 new arguments for specifying platform for benchmarks: `--cpu`, `--gpu`, `--tpu`. This allows us to set the proper device for connecting to TPUs outside of colab, where `Device.defaultXLA` does not automatically pick up TPUs.
+ Lint.
> Add platform arguments to benchmarks

- Gym/PPO/ActorCritic.swift
- Gym/PPO/Agent.swift
- Gym/PPO/Categorical.swift
- Gym/PPO/Gathering.swift
- Gym/PPO/Memory.swift
- Gym/PPO/PPO.swift
- Gym/PPO/main.swift
- Package.swift
Like DQN (PR #617), Proximal Policy Optimization (PPO) is another widely used reinforcement learning algorithm. Proposed by [Schulman et al. in 2017](https://github.com/tensorflow/swift-models/pull/617), PPO is an on-policy policy gradient algorithm that serves as a standard baselines for both environments with discrete and continuous action spaces.
There are two versions of PPO: PPO-Clip and PPO-Penalty. This code implements PPO-Clip, the more popular version.
- ~If performance is subpar, will implement [GAE](https://arxiv.org/abs/1506.02438)~
> Implement Proximal Policy Optimization

- CycleGAN/CLI.swift
- Examples/Fractals/main.swift
- pix2pix/CLI.swift
In order to silence a few deprecation warnings, this updates default arguments for ArgumentParser to the new syntax used in recent versions of that module.
> Updating parameters to match current ArgumentParser version

- Examples/BERT-CoLA/main.swift
Fixes type checking error after the [`swift-DEVELOPMENT-SNAPSHOT-2020-08-31-a -> tensorflow` merge](https://github.com/apple/swift/pull/33755).
```
$ swift build
/swift-models/Examples/BERT-CoLA/main.swift:69:3: error: generic parameter 'Entropy' could not be inferred
) { (example: CoLAExample) -> CoLA.LabeledTextBatch in
^
```
An alternative fix is explicitly specifying `CoLA<SystemRandomNumberGenerator>.LabeledTextBatch` as the closure result type.
The underlying issue is probably related to closure result type inference changes.
> Remove explicit `CoLA.init` trailing closure signature.

- Tests/SupportTests/AnyLayerTests.swift
Two very similar `AnyLayer` assertions are failing with the new toolchain build. Temporarily disable until @shadaj can help clarify the purpose of the test and resolve once new toolchains are published.
```
Test Case 'AnyLayerTests.testOpaqueScalarEquality' started at 2020-09-08 09:48:48.541
/swift-models/Tests/SupportTests/AnyLayerTests.swift:131: error: AnyLayerTests.testOpaqueScalarEquality : XCTAssertEqual failed: ("AnyLayerTangentVector<Float>(box: ModelSupport.ConcreteAnyLayerTangentVectorBox<ModelSupport.AnyLayerTangentVector<Swift.Float>.OpaqueScalar>)") is not equal to ("AnyLayerTangentVector<Float>(box: ModelSupport.ConcreteAnyLayerTangentVectorBox<TensorFlow.Dense<Swift.Float>.TangentVector>)") - 
/swift-models/Tests/SupportTests/AnyLayerTests.swift:132: error: …
```
> Disable failing AnyLayer tests

- Support/Image.swift
When drawing lines on images, if one of the points in the line is outside the image bounds, it causes a crash in the line drawing function. This PR fixes that.
> Fix out of bound points crashing line drawing function

- CMakeLists.txt
The `master` branch of ArgumentParser has been renamed to `main`, so we need to update the one dependency on this in our CMakeLists.
> ArgumentParser migration from master->main

- Support/FoundationFileSystem.swift
PR #668 added an `append()` method to the FileSystem protocol and an implementation in FoundationFileSystem. This implementation used FileHandle and several methods which have had their signatures change between macOS 10.15 (Catalina) and 10.16 (Big Sur). The current implementation uses the new interface, which will build with the latest Linux toolchain but will not build on the current macOS 10.15 (Catalina).
This provides the older interface for use when building on macOS, and the newer one for other OS versions. Once Big Sur is the dominant build environment for macOS, we can remove this fallback.
> Adding Catalina-compatible FileHandle operations

- Examples/Fractals/Notebook/Mandelbrot.ipynb
The extraneous comma prevented the notebook from loading in colab.
> Removed extraneous comma

- Examples/GrowingNeuralCellularAutomata/GrowingNeuralCellularAutomata.ipynb
The links did't point the master branch of tensorflow/swift-model.
> Fixed links to Colab and GitHub

- Support/FoundationFileSystem.swift
In PR #670, the parameter to FoundationFileSystem's append() method was changed from `value` to `suffix` on the Linux side, but not for macOS. This causes model compilation to fail on macOS.
This quick fix updates the macOS side to re-enable building models there.
> Update FileHandler value -> suffix to match the changes to the Linux side

- pix2pix/main.swift
Use the Swift provided random number generation rather than the C
function which is not portable.  This enables building pix2pix on
Windows.
> pix2pix: use `Int32.random` instead of `__C.random`

- CycleGAN/main.swift
Use the Swift provided random number generation rather than the C
function which is not portable.  This enables building CycleGAN on
Windows.
> CycleGAN: use `Int32.random` instead of `__C.random`

- BenchmarksCore/Models/WordSeg.swift
- Examples/WordSeg/main.swift
- Models/Text/WordSeg/SemiRing.swift
Importing `ucrt` is insufficient since we rely on the type-generic
operation to convert the `Float` to what would be operations on
`Double` otherwise.
> WordSeg: repair build on Windows

- Examples/Shallow-Water-PDE/ArrayLoopSolution.swift
- Examples/Shallow-Water-PDE/TensorConvSolution.swift
- Examples/Shallow-Water-PDE/TensorLoopSolution.swift
- Examples/Shallow-Water-PDE/TensorSliceSolution.swift
We need to import `MSVCRT` (or rather the new name of `CRT`) to get the
type-generic operations as the C library functions which are referenced
here expect double values but the values being used are single precision
(`Float`) which fails to type-check.
> Shallow Water PDE: make build on Windows

- Models/Text/CMakeLists.txt
Repair the CMake based build which was under-specifying dependencies.
> build: correct missing dependency for `Models`

- README.md
Windows snapshots as of 10/28 have SwiftPM in the snapshots and works
to build the models.  Update the docs for build instructions.
> docs: update build docs for Windows

- Examples/GPT2-Inference/README.md
Update the instructions for the 0.12 release and the 10/29 snapshot.
This allows for a much simpler build invocation.
> GPT2 UI: update instructions for Windows

- Package.swift
This should make it possible to build packages that depend on multiple packages that depend on different version ranges of swift-benchmark (as long as there is at least one compatible version).
> make swift-benchmark dependency use version

- Models/Text/WordSeg/Model.swift
This makes it compile after I remove the hardcoded tangentvector conformances. (apple/swift@2dbdc55)
> make it compile without hardcoded tangentvector conformances

- Models/Text/WordSeg/Model.swift
Since TF-433 was fixed, we can remove all the workarkounds for (non-active) try-apply.
For example, calls to `Array.map(_:)` and `Bool.&&`.
> Revert non-active try-apply differentiation workarounds

- Datasets/WordSeg/WordSegDataset.swift
- Tests/DatasetsTests/TextUnsupervised/TextUnsupervisedTests.swift
- Tests/DatasetsTests/WordSeg/WordSegDatasetTests.swift
The `testCreateWikiText103WithoutBpe` test will always fail [a precondition](https://github.com/tensorflow/swift-models/blob/main/Datasets/TextUnsupervised/TextUnsupervised.swift#L212) because it sets bpe to nil, while `encodedFileName` is also nil for that dataset. This test case is not active on Linux, but will run on macOS, where it crashes tests. As a result, I've removed this test case.
Additionally, the WordSegDataset used a hardcoded path to /dev/null when no filename is specified for two components. Direct access to /dev/null is blocked on macOS, and is problematic for Windows. I've replaced this with creation of an empty Data instance if the file name is missing.
With these changes, all tests now pass on macOS.
> Repairing two text-based tests on macOS

- CMakeLists.txt
SwiftProtobuf just moved over to main as the default branch, so this updates the reference in CMake to allow it to build again.
> Update CMakeLists for SwiftProtobuf's main migration

- TrainingLoop/Metrics.swift
> add top 5 accuracy metric

- CMakeLists.txt
- Models/Text/CMakeLists.txt
- Models/Text/WordSeg/Lattice.swift
- Models/Text/WordSeg/Model.swift
- Models/Text/WordSeg/SemiRing.swift
- Package.swift
- Support/AnyLayer.swift
- Support/AnyLayerTangentVector.swift
- Support/CMakeLists.txt
- Tests/SupportTests/AnyLayerTests.swift
- cmake/modules/CheckSwiftSourceCompiles.cmake
This provides the needed Numerics dependency, as well as missing _Differentiation imports, to support building while using a stock toolchain with swift-apis. For now, the AnyLayer type has been gated off from the stock toolchain until it can be reworked to support the new VectorProtocol.
To build this successfully under Swift Package Manager with the stock toolchain, you'll need to provide the `TENSORFLOW_USE_STANDARD_TOOLCHAIN` flag:
```sh
swift build -Xswiftc -D TENSORFLOW_USE_STANDARD_TOOLCHAIN
```
This is needed to avoid a conflict caused by the use of Numerics in the stock toolchain. CMake should detect this automatically, and does not require any additional command-line options.
> Initial compatibility with stock toolchain

- docker/presubmit_build.sh
I copied this from the internal script in google3, and modified it to pass a flag when building with a stock toolchain.
I'll also make a CL that deletes the script from google3 and calls this one instead.
> add presubmit_build.sh that passes a flag to swiftpm if it is a stock toolchain

- CMakeLists.txt
- Models/Text/CMakeLists.txt
- Models/Text/WordSeg/Model.swift
- Package.swift
- Support/AnyLayer.swift
- Support/AnyLayerTangentVector.swift
- Support/CMakeLists.txt
- Tests/SupportTests/AnyLayerTests.swift
AnyLayer can now build using both the stock (+swift-apis) and current Swift for TensorFlow toolchains, so the define-based conditionals have been removed. This also removes the need for explicit Numerics imports, due to Numerics now being exported from swift-apis.
Due to slight differences in ElementaryFunctions, I've temporarily disabled a handful of exponential and logarithm variants within AnyLayer (which weren't being used for anything currently, anyways).
With these changes, swift-models can now build without any extra compiler flags for both the current Swift for TensorFlow toolchains and the new stock (+swift-apis) toolchains.
> Stock toolchain cleanup

- TrainingLoop/Metrics.swift
Within the statistics callback introduced in PR #718 is a temporary tensor that by default is being placed on the eager device. This is causing a crash at runtime in examples using that callback on X10 devices, so this introduces a quick fix to place that on an appropriate device.
With this, the previously failing examples now run correctly with X10.
> Fix for device placement when calculating statistics

- README.md
There are a lot of examples, models, and components contained within this repository. To highlight everything that resides here, this reworks the front-page README to act as an index for the examples and modules of interest within swift-models.
> Documenting models and components

- docker/Dockerfile
HTTP2 curl downloads are intermittently failing on GCS buckets, so this forces HTTP 1.1 usage with the toolchain downloads to unblock CI.
> Work around intermittent toolchain download failures

- pix2pix/CMakeLists.txt
This is a quick fix to get the pix2pix CMake target building again.
> Repairing CMakeLists for pix2pix

- Models/Text/GPT2/GPT2.swift
OpenAI migrated their hosting to Azure, so this updates the default GPT-2 checkpoint location to where it now resides. This fixes the few failing tests we are experiencing as a result of this move.
> Moving GPT-2 checkpoint location to its new host

- Datasets/CIFAR100/CIFAR100.swift
- Datasets/CMakeLists.txt
- Examples/BigTransfer-CIFAR100/CMakeLists.txt
- Examples/BigTransfer-CIFAR100/README.md
- Examples/BigTransfer-CIFAR100/main.swift
- Examples/CMakeLists.txt
- Models/ImageClassification/BigTransfer.swift
- Models/ImageClassification/CMakeLists.txt
- Package.swift
- Tests/DatasetsTests/CIFAR100/CIFAR100Tests.swift
- Tests/DatasetsTests/CMakeLists.txt
- Tests/DatasetsTests/XCTestManifests.swift
- Tests/ImageClassificationTests/Inference.swift
**Resubmitting with proper commit history for google-cla bot.**
Hey S4TF Team!
I've re-implemented the Big Transfer (BiT): General Visual Representation Learning (https://arxiv.org/abs/1912.11370) paper in Swift for Tensorflow. Through this process, I've also added support for CIFAR-100 by slightly modifying the existing CIFAR-10 dataset, as well as implemented Mixup, a StandardizedConv2D layer, and more.
Let me know your thoughts on the code! I've done a lot of cleanup and worked to replicate the existing project structure / testing patterns.
Andrew Marmon
> Big Transfer
